@echo off
REM ────────────────────────────────────────────────────────────────────────────
REM AI-DLC Setup for Kiro — Windows CMD
REM Downloads the latest AI-DLC release and installs steering files.
REM Usage: setup-aidlc.bat [workspace-path]
REM ────────────────────────────────────────────────────────────────────────────
setlocal enabledelayedexpansion

set "WORKSPACE=%~1"
if "%WORKSPACE%"=="" set "WORKSPACE=%CD%"

set "POWER_PATH=%~2"
if "%POWER_PATH%"=="" (
    REM Resolve power path from this script's location
    for %%I in ("%~dp0..") do set "POWER_PATH=%%~fI"
)

REM Resolve to absolute path
pushd "%WORKSPACE%" 2>nul
if errorlevel 1 (
    echo ERROR: Workspace path not found: %WORKSPACE%
    exit /b 1
)
set "WORKSPACE=%CD%"
popd

set "GITHUB_API=https://api.github.com/repos/awslabs/aidlc-workflows/releases/latest"
set "TMP_DIR=%WORKSPACE%\.aidlc-setup-tmp-%RANDOM%"

echo ==^> AI-DLC Setup for Kiro
echo     Workspace:  %WORKSPACE%
echo     Power path: %POWER_PATH%

mkdir "%TMP_DIR%" 2>nul

REM ── Check for curl (available on Windows 10+) ─────────────────────────────
where curl >nul 2>&1
if errorlevel 1 (
    echo ERROR: curl not found. Windows 10+ includes curl by default.
    echo        Please install curl or use the PowerShell script instead.
    goto :cleanup
)

REM ── Fetch latest release info ──────────────────────────────────────────────
echo ==^> Querying GitHub for latest release...
set "RELEASE_JSON=%TMP_DIR%\release.json"
curl -sL -H "User-Agent: aidlc-setup" "%GITHUB_API%" -o "%RELEASE_JSON%"

REM Parse tag_name — extract version between quotes after tag_name
for /f "tokens=2 delims=:" %%a in ('findstr /C:"tag_name" "%RELEASE_JSON%"') do (
    set "TAG_RAW=%%a"
)
REM Clean up the tag value — remove quotes, commas, spaces
set "TAG=!TAG_RAW: =!"
set "TAG=!TAG:"=!"
set "TAG=!TAG:,=!"

REM Parse the ai-dlc-rules zip URL
for /f "delims=" %%a in ('findstr /C:"ai-dlc-rules" "%RELEASE_JSON%" ^| findstr /C:"browser_download_url"') do (
    set "URL_LINE=%%a"
)
REM Extract URL from the line
for /f "tokens=2 delims= " %%u in ("!URL_LINE!") do (
    set "ASSET_URL=%%~u"
)
REM Remove trailing quote and comma if present
set "ASSET_URL=!ASSET_URL:"=!"
set "ASSET_URL=!ASSET_URL:,=!"

if "!ASSET_URL!"=="" (
    echo ERROR: Could not find AI-DLC rules zip in the latest release.
    goto :cleanup
)

echo     Latest release: !TAG!
echo     Asset URL: !ASSET_URL!

REM ── Download ───────────────────────────────────────────────────────────────
set "ZIP_FILE=%TMP_DIR%\aidlc-rules.zip"
echo ==^> Downloading...
curl -sL "!ASSET_URL!" -o "%ZIP_FILE%"

REM ── Extract ────────────────────────────────────────────────────────────────
set "EXTRACT_DIR=%TMP_DIR%\extracted"
mkdir "%EXTRACT_DIR%" 2>nul
echo ==^> Extracting...
tar -xf "%ZIP_FILE%" -C "%EXTRACT_DIR%" 2>nul
if errorlevel 1 (
    echo ERROR: Failed to extract zip. tar is required ^(Windows 10+^).
    goto :cleanup
)

REM ── Locate extracted folders ───────────────────────────────────────────────
set "RULES_BASE="
set "DETAILS_BASE="

for /f "delims=" %%d in ('dir /s /b /ad "%EXTRACT_DIR%\aws-aidlc-rules" 2^>nul') do (
    if not defined RULES_BASE set "RULES_BASE=%%d"
)
for /f "delims=" %%d in ('dir /s /b /ad "%EXTRACT_DIR%\aws-aidlc-rule-details" 2^>nul') do (
    if not defined DETAILS_BASE set "DETAILS_BASE=%%d"
)

if not defined RULES_BASE (
    echo ERROR: aws-aidlc-rules directory not found in the release zip.
    goto :cleanup
)
if not defined DETAILS_BASE (
    echo ERROR: aws-aidlc-rule-details directory not found in the release zip.
    goto :cleanup
)

REM ── Install into Kiro workspace ────────────────────────────────────────────
set "STEERING_DEST=%WORKSPACE%\.kiro\steering\aws-aidlc-rules"
set "DETAILS_DEST=%WORKSPACE%\.kiro\aws-aidlc-rule-details"

echo ==^> Installing steering files...

REM Remove old copies if present
if exist "%STEERING_DEST%" rmdir /s /q "%STEERING_DEST%"
if exist "%DETAILS_DEST%" rmdir /s /q "%DETAILS_DEST%"

REM Create directories and copy
mkdir "%WORKSPACE%\.kiro\steering" 2>nul
xcopy "%RULES_BASE%" "%STEERING_DEST%\" /E /I /Q /Y >nul
xcopy "%DETAILS_BASE%" "%DETAILS_DEST%\" /E /I /Q /Y >nul

REM ── Install this power's own steering files (enforcement rules) ──────────
set "POWER_STEERING_SRC=%POWER_PATH%\steering"
if exist "%POWER_STEERING_SRC%\aidlc-*.md" (
    for %%F in ("%POWER_STEERING_SRC%\aidlc-*.md") do (
        copy /Y "%%F" "%WORKSPACE%\.kiro\steering\" >nul
        echo     Installed steering: %%~nxF
    )
)

REM ── Write the canonical agent hook (source of truth: POWER.md) ───────────
set "HOOKS_DEST=%WORKSPACE%\.kiro\hooks"
set "HOOK_FILE=%HOOKS_DEST%\aidlc-workflow-prompt.kiro.hook"

echo ==^> Installing agent hook...
mkdir "%HOOKS_DEST%" 2>nul

REM Hook JSON is base64-encoded to avoid CMD quote-escaping issues.
REM To regenerate: base64 < .aidlc-hook-tmp.json | tr -d '\n'
set "HOOK_B64=ewogICJlbmFibGVkIjogdHJ1ZSwKICAibmFtZSI6ICJBSS1ETEMgV29ya2Zsb3cgUHJvbXB0IiwKICAiZGVzY3JpcHRpb24iOiAiQXNrcyB0aGUgdXNlciBhdCB0aGUgc3RhcnQgb2YgYSBjb252ZXJzYXRpb24gd2hldGhlciB0aGV5IHdhbnQgdG8gdXNlIHRoZSBBSS1ETEMgd29ya2Zsb3csIHJ1bnMgd29ya3NwYWNlIGRldGVjdGlvbiAoZ3JlZW5maWVsZCB2cyBicm93bmZpZWxkKSwgcHJlc2VudHMgY2xpY2thYmxlIHBoYXNlIHNlbGVjdGlvbiwgZ2F0aGVycyBjb250ZXh0IGZyb20gZWFybGllci1waGFzZSBhcnRpZmFjdHMgYWNyb3NzIHRoZSBlbnRpcmUgd29ya3NwYWNlLCB0aGVuIHByb2NlZWRzLiIsCiAgInZlcnNpb24iOiAiMSIsCiAgIndoZW4iOiB7CiAgICAidHlwZSI6ICJwcm9tcHRTdWJtaXQiCiAgfSwKICAidGhlbiI6IHsKICAgICJ0eXBlIjogImFza0FnZW50IiwKICAgICJwcm9tcHQiOiAiQmVmb3JlIHByb2NlZWRpbmcgd2l0aCB0aGUgdXNlcidzIHJlcXVlc3QsIGNoZWNrIGlmIEFJLURMQyBzdGVlcmluZyBmaWxlcyBhcmUgaW5zdGFsbGVkIGluIHRoaXMgd29ya3NwYWNlIChsb29rIGZvciAua2lyby9zdGVlcmluZy9hd3MtYWlkbGMtcnVsZXMvY29yZS13b3JrZmxvdy5tZCkuXG5cbklmIHRoZXkgZXhpc3QgYW5kIHlvdSBoYXZlIE5PVCBhbHJlYWR5IGFza2VkIHRoZSB1c2VyIGFib3V0IEFJLURMQyBpbiB0aGlzIGNvbnZlcnNhdGlvbiwgcHJlc2VudCB0aGUgQUktRExDIGNob2ljZSB0byB0aGUgdXNlci5cblxuPT0gU1RFUCAxOiBBc2sgWWVzL05vID09XG5cblBSRUZFUlJFRDogSWYgdGhlIHVzZXJJbnB1dCB0b29sIGlzIGF2YWlsYWJsZSAoU3BlYyBtb2RlKSwgdXNlIGl0LiBDYWxsIHVzZXJJbnB1dCB3aXRoOlxuLSByZWFzb246IFwiZ2VuZXJhbC1xdWVzdGlvblwiXG4tIHF1ZXN0aW9uOiBcIkkgc2VlIEFJLURMQyBpcyBzZXQgdXAgaW4gdGhpcyB3b3Jrc3BhY2UuIFdvdWxkIHlvdSBsaWtlIHRvIHVzZSB0aGUgQUktRExDIHdvcmtmbG93IGZvciB0aGlzIHRhc2s/XCJcbi0gb3B0aW9uczogW3tcInRpdGxlXCI6IFwiWWVzLCB1c2UgQUktRExDXCIsIFwiZGVzY3JpcHRpb25cIjogXCJBY3RpdmF0ZSB0aGUgQUktRExDIHdvcmtmbG93IGFuZCBzZWxlY3QgYSBzdGFydGluZyBwaGFzZVwiLCBcInJlY29tbWVuZGVkXCI6IHRydWV9LCB7XCJ0aXRsZVwiOiBcIk5vIHRoYW5rc1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiUHJvY2VlZCBub3JtYWxseSB3aXRob3V0IEFJLURMQ1wifV1cblxuRkFMTEJBQ0s6IElmIHVzZXJJbnB1dCBpcyBOT1QgYXZhaWxhYmxlIChWaWJlIG1vZGUpLCByZXBseSB3aXRoIHRoaXMgZXhhY3QgbWFya2Rvd246XG5cbkkgc2VlIEFJLURMQyBpcyBzZXQgdXAgaW4gdGhpcyB3b3Jrc3BhY2UuIFdvdWxkIHlvdSBsaWtlIHRvIHVzZSB0aGUgQUktRExDIHdvcmtmbG93IGZvciB0aGlzIHRhc2s/XG5cbjEuICoqWWVzLCB1c2UgQUktRExDKiogLSBBY3RpdmF0ZSB0aGUgQUktRExDIHdvcmtmbG93IGFuZCBzZWxlY3QgYSBzdGFydGluZyBwaGFzZVxuMi4gKipObyB0aGFua3MqKiAtIFByb2NlZWQgbm9ybWFsbHkgd2l0aG91dCBBSS1ETENcblxuUmVwbHkgd2l0aCB0aGUgbnVtYmVyICgxIG9yIDIpIG9yIHRoZSBvcHRpb24gbmFtZS5cblxuPT0gU1RFUCAyOiBXb3Jrc3BhY2UgRGV0ZWN0aW9uIChvbmx5IGlmIHVzZXIgY2hvc2UgWWVzKSA9PVxuXG5JZiB0aGUgdXNlciBzZWxlY3RlZCBcIlllcywgdXNlIEFJLURMQ1wiIChvciByZXBsaWVkIDEveWVzKSwgRE8gTk9UIHByZXNlbnQgdGhlIHBoYXNlIGxpc3QgeWV0LiBGaXJzdCBydW4gd29ya3NwYWNlIGRldGVjdGlvbiBieSBsb2FkaW5nIGFuZCBmb2xsb3dpbmcgLmtpcm8vYXdzLWFpZGxjLXJ1bGUtZGV0YWlscy9pbmNlcHRpb24vd29ya3NwYWNlLWRldGVjdGlvbi5tZC4gU2lsZW50bHkgc2NhbiB0aGUgd29ya3NwYWNlIGZvciBleGlzdGluZyBzb3VyY2UgY29kZSBmaWxlcyAoLmphdmEsIC5weSwgLmpzLCAudHMsIC5qc3gsIC50c3gsIC5rdCwgLmt0cywgLnNjYWxhLCAuZ3Jvb3Z5LCAuZ28sIC5ycywgLnJiLCAucGhwLCAuYywgLmgsIC5jcHAsIC5ocHAsIC5jYywgLmNzLCAuZnMpIGFuZCBidWlsZCBmaWxlcyAocG9tLnhtbCwgcGFja2FnZS5qc29uLCBidWlsZC5ncmFkbGUsIENhcmdvLnRvbWwsIGdvLm1vZCwgR2VtZmlsZSwgcmVxdWlyZW1lbnRzLnR4dCwgcHlwcm9qZWN0LnRvbWwsIGV0Yy4pLCBleGNsdWRpbmcgdGhlIC5raXJvIGFuZCBhaWRsYy1kb2NzIGRpcmVjdG9yaWVzLiBEbyBOT1QgYXNrIHRoZSB1c2VyIC0gZGV0ZWN0IGF1dG9tYXRpY2FsbHkuXG5cbi0gSWYgTk8gc291cmNlIG9yIGJ1aWxkIGZpbGVzIGFyZSBmb3VuZCBvdXRzaWRlIC5raXJvIGFuZCBhaWRsYy1kb2NzOiBwcm9qZWN0X3R5cGUgPSBncmVlbmZpZWxkXG4tIElmIHNvdXJjZSBvciBidWlsZCBmaWxlcyBhcmUgZm91bmQ6IHByb2plY3RfdHlwZSA9IGJyb3duZmllbGRcblxuPT0gU1RFUCAzOiBQcmVzZW50IHBoYXNlIHNlbGVjdGlvbiBmb3IgdGhlIGRldGVjdGVkIHR5cGUgPT1cblxuRm9yIEdSRUVORklFTEQ6IHByZXNlbnQgMTIgcGhhc2VzIHN0YXJ0aW5nIHdpdGggXCJSZXF1aXJlbWVudHMgYW5hbHlzaXMgYW5kIHZhbGlkYXRpb25cIi5cbkZvciBCUk9XTkZJRUxEOiBwcmVzZW50IDEzIHBoYXNlcyB3aXRoIFwiUmV2ZXJzZSBFbmdpbmVlcmluZ1wiIGFzIHBoYXNlIDEuXG5cblBSRUZFUlJFRCAoU3BlYyBtb2RlKTogQ2FsbCB1c2VySW5wdXQgd2l0aDpcbi0gcmVhc29uOiBcImdlbmVyYWwtcXVlc3Rpb25cIlxuLSBxdWVzdGlvbjogXCJEZXRlY3RlZCA8Z3JlZW5maWVsZHxicm93bmZpZWxkPiBwcm9qZWN0LiBXaGljaCBBSS1ETEMgcGhhc2Ugd291bGQgeW91IGxpa2UgdG8gc3RhcnQgZnJvbT9cIiAoc3Vic3RpdHV0ZSB0aGUgZGV0ZWN0ZWQgdHlwZSlcbi0gb3B0aW9ucyBmb3IgR1JFRU5GSUVMRDogW3tcInRpdGxlXCI6IFwiMS4gUmVxdWlyZW1lbnRzIGFuYWx5c2lzIGFuZCB2YWxpZGF0aW9uXCIsIFwiZGVzY3JpcHRpb25cIjogXCJHYXRoZXIsIGFuYWx5emUsIGFuZCB2YWxpZGF0ZSBwcm9qZWN0IHJlcXVpcmVtZW50c1wiLCBcInJlY29tbWVuZGVkXCI6IHRydWV9LCB7XCJ0aXRsZVwiOiBcIjIuIFVzZXIgc3RvcnkgY3JlYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkNyZWF0ZSB1c2VyIHN0b3JpZXMgYW5kIGFjY2VwdGFuY2UgY3JpdGVyaWFcIn0sIHtcInRpdGxlXCI6IFwiMy4gQXBwbGljYXRpb24gRGVzaWduXCIsIFwiZGVzY3JpcHRpb25cIjogXCJEZXNpZ24gdGhlIGFwcGxpY2F0aW9uIGFyY2hpdGVjdHVyZVwifSwge1widGl0bGVcIjogXCI0LiBDcmVhdGluZyB1bml0cyBvZiB3b3JrIGZvciBwYXJhbGxlbCBkZXZlbG9wbWVudFwiLCBcImRlc2NyaXB0aW9uXCI6IFwiQnJlYWsgZG93biB3b3JrIGludG8gcGFyYWxsZWxpemFibGUgdGFza3NcIn0sIHtcInRpdGxlXCI6IFwiNS4gUmlzayBhc3Nlc3NtZW50IGFuZCBjb21wbGV4aXR5IGV2YWx1YXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIklkZW50aWZ5IHJpc2tzIGFuZCBlc3RpbWF0ZSBjb21wbGV4aXR5XCJ9LCB7XCJ0aXRsZVwiOiBcIjYuIERldGFpbGVkIGNvbXBvbmVudCBkZXNpZ25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkRlc2lnbiBpbmRpdmlkdWFsIGNvbXBvbmVudHMgYW5kIGludGVyZmFjZXNcIn0sIHtcInRpdGxlXCI6IFwiNy4gQ29kZSBnZW5lcmF0aW9uIGFuZCBpbXBsZW1lbnRhdGlvblwiLCBcImRlc2NyaXB0aW9uXCI6IFwiR2VuZXJhdGUgYW5kIGltcGxlbWVudCBjb2RlXCJ9LCB7XCJ0aXRsZVwiOiBcIjguIEJ1aWxkIGNvbmZpZ3VyYXRpb24gYW5kIHRlc3Rpbmcgc3RyYXRlZ2llc1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiU2V0IHVwIGJ1aWxkIHBpcGVsaW5lcyBhbmQgdGVzdCBmcmFtZXdvcmtzXCJ9LCB7XCJ0aXRsZVwiOiBcIjkuIFF1YWxpdHkgYXNzdXJhbmNlIGFuZCB2YWxpZGF0aW9uXCIsIFwiZGVzY3JpcHRpb25cIjogXCJSdW4gdGVzdHMgYW5kIGNvZGUgcmV2aWV3c1wifSwge1widGl0bGVcIjogXCIxMC4gRGVwbG95bWVudCBhdXRvbWF0aW9uIGFuZCBpbmZyYXN0cnVjdHVyZVwiLCBcImRlc2NyaXB0aW9uXCI6IFwiQXV0b21hdGUgZGVwbG95bWVudCBhbmQgcHJvdmlzaW9uIGluZnJhc3RydWN0dXJlXCJ9LCB7XCJ0aXRsZVwiOiBcIjExLiBNb25pdG9yaW5nIGFuZCBvYnNlcnZhYmlsaXR5IHNldHVwXCIsIFwiZGVzY3JpcHRpb25cIjogXCJTZXQgdXAgbG9nZ2luZywgbWV0cmljcywgYW5kIGRhc2hib2FyZHNcIn0sIHtcInRpdGxlXCI6IFwiMTIuIFByb2R1Y3Rpb24gcmVhZGluZXNzIHZhbGlkYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkZpbmFsIGNoZWNrcyBiZWZvcmUgZ29pbmcgbGl2ZVwifV1cbi0gb3B0aW9ucyBmb3IgQlJPV05GSUVMRDogW3tcInRpdGxlXCI6IFwiMS4gUmV2ZXJzZSBFbmdpbmVlcmluZ1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiQW5hbHl6ZSBleGlzdGluZyBjb2RlYmFzZSB0byByZWNvbnN0cnVjdCByZXF1aXJlbWVudHMsIGFyY2hpdGVjdHVyZSwgYW5kIGRlc2lnbiBhcnRpZmFjdHNcIiwgXCJyZWNvbW1lbmRlZFwiOiB0cnVlfSwge1widGl0bGVcIjogXCIyLiBSZXF1aXJlbWVudHMgYW5hbHlzaXMgYW5kIHZhbGlkYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkdhdGhlciwgYW5hbHl6ZSwgYW5kIHZhbGlkYXRlIHByb2plY3QgcmVxdWlyZW1lbnRzXCJ9LCB7XCJ0aXRsZVwiOiBcIjMuIFVzZXIgc3RvcnkgY3JlYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkNyZWF0ZSB1c2VyIHN0b3JpZXMgYW5kIGFjY2VwdGFuY2UgY3JpdGVyaWFcIn0sIHtcInRpdGxlXCI6IFwiNC4gQXBwbGljYXRpb24gRGVzaWduXCIsIFwiZGVzY3JpcHRpb25cIjogXCJEZXNpZ24gdGhlIGFwcGxpY2F0aW9uIGFyY2hpdGVjdHVyZVwifSwge1widGl0bGVcIjogXCI1LiBDcmVhdGluZyB1bml0cyBvZiB3b3JrIGZvciBwYXJhbGxlbCBkZXZlbG9wbWVudFwiLCBcImRlc2NyaXB0aW9uXCI6IFwiQnJlYWsgZG93biB3b3JrIGludG8gcGFyYWxsZWxpemFibGUgdGFza3NcIn0sIHtcInRpdGxlXCI6IFwiNi4gUmlzayBhc3Nlc3NtZW50IGFuZCBjb21wbGV4aXR5IGV2YWx1YXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIklkZW50aWZ5IHJpc2tzIGFuZCBlc3RpbWF0ZSBjb21wbGV4aXR5XCJ9LCB7XCJ0aXRsZVwiOiBcIjcuIERldGFpbGVkIGNvbXBvbmVudCBkZXNpZ25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkRlc2lnbiBpbmRpdmlkdWFsIGNvbXBvbmVudHMgYW5kIGludGVyZmFjZXNcIn0sIHtcInRpdGxlXCI6IFwiOC4gQ29kZSBnZW5lcmF0aW9uIGFuZCBpbXBsZW1lbnRhdGlvblwiLCBcImRlc2NyaXB0aW9uXCI6IFwiR2VuZXJhdGUgYW5kIGltcGxlbWVudCBjb2RlXCJ9LCB7XCJ0aXRsZVwiOiBcIjkuIEJ1aWxkIGNvbmZpZ3VyYXRpb24gYW5kIHRlc3Rpbmcgc3RyYXRlZ2llc1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiU2V0IHVwIGJ1aWxkIHBpcGVsaW5lcyBhbmQgdGVzdCBmcmFtZXdvcmtzXCJ9LCB7XCJ0aXRsZVwiOiBcIjEwLiBRdWFsaXR5IGFzc3VyYW5jZSBhbmQgdmFsaWRhdGlvblwiLCBcImRlc2NyaXB0aW9uXCI6IFwiUnVuIHRlc3RzIGFuZCBjb2RlIHJldmlld3NcIn0sIHtcInRpdGxlXCI6IFwiMTEuIERlcGxveW1lbnQgYXV0b21hdGlvbiBhbmQgaW5mcmFzdHJ1Y3R1cmVcIiwgXCJkZXNjcmlwdGlvblwiOiBcIkF1dG9tYXRlIGRlcGxveW1lbnQgYW5kIHByb3Zpc2lvbiBpbmZyYXN0cnVjdHVyZVwifSwge1widGl0bGVcIjogXCIxMi4gTW9uaXRvcmluZyBhbmQgb2JzZXJ2YWJpbGl0eSBzZXR1cFwiLCBcImRlc2NyaXB0aW9uXCI6IFwiU2V0IHVwIGxvZ2dpbmcsIG1ldHJpY3MsIGFuZCBkYXNoYm9hcmRzXCJ9LCB7XCJ0aXRsZVwiOiBcIjEzLiBQcm9kdWN0aW9uIHJlYWRpbmVzcyB2YWxpZGF0aW9uXCIsIFwiZGVzY3JpcHRpb25cIjogXCJGaW5hbCBjaGVja3MgYmVmb3JlIGdvaW5nIGxpdmVcIn1dXG5cbkZBTExCQUNLIChWaWJlIG1vZGUpOlxuXG5JZiBHUkVFTkZJRUxELCByZXBseSB3aXRoIHRoaXMgZXhhY3QgbWFya2Rvd246XG5cbkRldGVjdGVkOiBHcmVlbmZpZWxkIHByb2plY3QgKG5vIGV4aXN0aW5nIGNvZGUpLlxuXG5XaGljaCBBSS1ETEMgcGhhc2Ugd291bGQgeW91IGxpa2UgdG8gc3RhcnQgZnJvbT9cblxuMS4gKipSZXF1aXJlbWVudHMgYW5hbHlzaXMgYW5kIHZhbGlkYXRpb24qKiAtIEdhdGhlciwgYW5hbHl6ZSwgYW5kIHZhbGlkYXRlIHByb2plY3QgcmVxdWlyZW1lbnRzXG4yLiAqKlVzZXIgc3RvcnkgY3JlYXRpb24qKiAtIENyZWF0ZSB1c2VyIHN0b3JpZXMgYW5kIGFjY2VwdGFuY2UgY3JpdGVyaWFcbjMuICoqQXBwbGljYXRpb24gRGVzaWduKiogLSBEZXNpZ24gdGhlIGFwcGxpY2F0aW9uIGFyY2hpdGVjdHVyZVxuNC4gKipDcmVhdGluZyB1bml0cyBvZiB3b3JrIGZvciBwYXJhbGxlbCBkZXZlbG9wbWVudCoqIC0gQnJlYWsgZG93biB3b3JrIGludG8gcGFyYWxsZWxpemFibGUgdGFza3NcbjUuICoqUmlzayBhc3Nlc3NtZW50IGFuZCBjb21wbGV4aXR5IGV2YWx1YXRpb24qKiAtIElkZW50aWZ5IHJpc2tzIGFuZCBlc3RpbWF0ZSBjb21wbGV4aXR5XG42LiAqKkRldGFpbGVkIGNvbXBvbmVudCBkZXNpZ24qKiAtIERlc2lnbiBpbmRpdmlkdWFsIGNvbXBvbmVudHMgYW5kIGludGVyZmFjZXNcbjcuICoqQ29kZSBnZW5lcmF0aW9uIGFuZCBpbXBsZW1lbnRhdGlvbioqIC0gR2VuZXJhdGUgYW5kIGltcGxlbWVudCBjb2RlXG44LiAqKkJ1aWxkIGNvbmZpZ3VyYXRpb24gYW5kIHRlc3Rpbmcgc3RyYXRlZ2llcyoqIC0gU2V0IHVwIGJ1aWxkIHBpcGVsaW5lcyBhbmQgdGVzdCBmcmFtZXdvcmtzXG45LiAqKlF1YWxpdHkgYXNzdXJhbmNlIGFuZCB2YWxpZGF0aW9uKiogLSBSdW4gdGVzdHMgYW5kIGNvZGUgcmV2aWV3c1xuMTAuICoqRGVwbG95bWVudCBhdXRvbWF0aW9uIGFuZCBpbmZyYXN0cnVjdHVyZSoqIC0gQXV0b21hdGUgZGVwbG95bWVudCBhbmQgcHJvdmlzaW9uIGluZnJhc3RydWN0dXJlXG4xMS4gKipNb25pdG9yaW5nIGFuZCBvYnNlcnZhYmlsaXR5IHNldHVwKiogLSBTZXQgdXAgbG9nZ2luZywgbWV0cmljcywgYW5kIGRhc2hib2FyZHNcbjEyLiAqKlByb2R1Y3Rpb24gcmVhZGluZXNzIHZhbGlkYXRpb24qKiAtIEZpbmFsIGNoZWNrcyBiZWZvcmUgZ29pbmcgbGl2ZVxuXG5SZXBseSB3aXRoIHRoZSBudW1iZXIgKDEtMTIpIG9yIHRoZSBwaGFzZSBuYW1lLlxuXG5JZiBCUk9XTkZJRUxELCByZXBseSB3aXRoIHRoaXMgZXhhY3QgbWFya2Rvd246XG5cbkRldGVjdGVkOiBCcm93bmZpZWxkIHByb2plY3QgKGV4aXN0aW5nIGNvZGUgZm91bmQpLlxuXG5XaGljaCBBSS1ETEMgcGhhc2Ugd291bGQgeW91IGxpa2UgdG8gc3RhcnQgZnJvbT9cblxuMS4gKipSZXZlcnNlIEVuZ2luZWVyaW5nKiogLSBBbmFseXplIGV4aXN0aW5nIGNvZGViYXNlIHRvIHJlY29uc3RydWN0IHJlcXVpcmVtZW50cywgYXJjaGl0ZWN0dXJlLCBhbmQgZGVzaWduIGFydGlmYWN0c1xuMi4gKipSZXF1aXJlbWVudHMgYW5hbHlzaXMgYW5kIHZhbGlkYXRpb24qKiAtIEdhdGhlciwgYW5hbHl6ZSwgYW5kIHZhbGlkYXRlIHByb2plY3QgcmVxdWlyZW1lbnRzXG4zLiAqKlVzZXIgc3RvcnkgY3JlYXRpb24qKiAtIENyZWF0ZSB1c2VyIHN0b3JpZXMgYW5kIGFjY2VwdGFuY2UgY3JpdGVyaWFcbjQuICoqQXBwbGljYXRpb24gRGVzaWduKiogLSBEZXNpZ24gdGhlIGFwcGxpY2F0aW9uIGFyY2hpdGVjdHVyZVxuNS4gKipDcmVhdGluZyB1bml0cyBvZiB3b3JrIGZvciBwYXJhbGxlbCBkZXZlbG9wbWVudCoqIC0gQnJlYWsgZG93biB3b3JrIGludG8gcGFyYWxsZWxpemFibGUgdGFza3NcbjYuICoqUmlzayBhc3Nlc3NtZW50IGFuZCBjb21wbGV4aXR5IGV2YWx1YXRpb24qKiAtIElkZW50aWZ5IHJpc2tzIGFuZCBlc3RpbWF0ZSBjb21wbGV4aXR5XG43LiAqKkRldGFpbGVkIGNvbXBvbmVudCBkZXNpZ24qKiAtIERlc2lnbiBpbmRpdmlkdWFsIGNvbXBvbmVudHMgYW5kIGludGVyZmFjZXNcbjguICoqQ29kZSBnZW5lcmF0aW9uIGFuZCBpbXBsZW1lbnRhdGlvbioqIC0gR2VuZXJhdGUgYW5kIGltcGxlbWVudCBjb2RlXG45LiAqKkJ1aWxkIGNvbmZpZ3VyYXRpb24gYW5kIHRlc3Rpbmcgc3RyYXRlZ2llcyoqIC0gU2V0IHVwIGJ1aWxkIHBpcGVsaW5lcyBhbmQgdGVzdCBmcmFtZXdvcmtzXG4xMC4gKipRdWFsaXR5IGFzc3VyYW5jZSBhbmQgdmFsaWRhdGlvbioqIC0gUnVuIHRlc3RzIGFuZCBjb2RlIHJldmlld3NcbjExLiAqKkRlcGxveW1lbnQgYXV0b21hdGlvbiBhbmQgaW5mcmFzdHJ1Y3R1cmUqKiAtIEF1dG9tYXRlIGRlcGxveW1lbnQgYW5kIHByb3Zpc2lvbiBpbmZyYXN0cnVjdHVyZVxuMTIuICoqTW9uaXRvcmluZyBhbmQgb2JzZXJ2YWJpbGl0eSBzZXR1cCoqIC0gU2V0IHVwIGxvZ2dpbmcsIG1ldHJpY3MsIGFuZCBkYXNoYm9hcmRzXG4xMy4gKipQcm9kdWN0aW9uIHJlYWRpbmVzcyB2YWxpZGF0aW9uKiogLSBGaW5hbCBjaGVja3MgYmVmb3JlIGdvaW5nIGxpdmVcblxuUmVwbHkgd2l0aCB0aGUgbnVtYmVyICgxLTEzKSBvciB0aGUgcGhhc2UgbmFtZS5cblxuPT0gU1RFUCA0OiBDb250ZXh0IEdhdGhlcmluZyAoc2lsZW50LCBubyB1c2VyIHByb21wdCkgPT1cblxuQWZ0ZXIgdGhlIHVzZXIgcGlja3MgYSBwaGFzZSwgYnV0IEJFRk9SRSBleGVjdXRpbmcgaXQsIHNpbGVudGx5IHNjYW4gdGhlIFdIT0xFIHdvcmtzcGFjZSBmb3IgYXJ0aWZhY3RzIHRoYXQgY291bGQgaW5mb3JtIGVhcmxpZXIgcGhhc2VzLiBEbyBOT1QgcHJvbXB0IHRoZSB1c2VyLiBEbyBOT1QgYXNrIHdoZXRoZXIgdG8gYmFja2ZpbGwuIEp1c3QgYWJzb3JiIHdoYXRldmVyIGV4aXN0cy5cblxuSWYgdGhlIHVzZXIgcGlja2VkIHBoYXNlIE4sIHRoZSBwcmlvciBwaGFzZXMgYXJlIDEuLk4tMS4gSWYgTiA9PSAxLCBza2lwIHRoaXMgc3RlcC5cblxuNC4xIFNDQU4gTE9DQVRJT05TXG5cbkxvb2sgRVZFUllXSEVSRSBpbiB0aGUgd29ya3NwYWNlLCBub3Qgb25seSBhaWRsYy1kb2NzLy4gU3BlY2lmaWNhbGx5OlxuXG5BLiBBSS1ETEMgY2Fub25pY2FsIGxvY2F0aW9uOlxuICAgLSBhaWRsYy1kb2NzL2luY2VwdGlvbi9yZXZlcnNlLWVuZ2luZWVyaW5nL1xuICAgLSBhaWRsYy1kb2NzL2luY2VwdGlvbi9yZXF1aXJlbWVudHMvXG4gICAtIGFpZGxjLWRvY3MvaW5jZXB0aW9uL3VzZXItc3Rvcmllcy9cbiAgIC0gYWlkbGMtZG9jcy9pbmNlcHRpb24vZGVzaWduL1xuICAgLSBhaWRsYy1kb2NzL2NvbnN0cnVjdGlvbi91bml0cy1vZi13b3JrL1xuICAgLSBhaWRsYy1kb2NzL2NvbnN0cnVjdGlvbi9yaXNrLWFzc2Vzc21lbnQvXG4gICAtIGFpZGxjLWRvY3MvY29uc3RydWN0aW9uL2NvbXBvbmVudC1kZXNpZ24vXG4gICAtIGFpZGxjLWRvY3MvY29uc3RydWN0aW9uL2NvZGUtZ2VuZXJhdGlvbi9cbiAgIC0gYWlkbGMtZG9jcy9jb25zdHJ1Y3Rpb24vYnVpbGQtY29uZmlnL1xuICAgLSBhaWRsYy1kb2NzL2NvbnN0cnVjdGlvbi9xYS9cbiAgIC0gYWlkbGMtZG9jcy9vcGVyYXRpb25zL2RlcGxveW1lbnQvXG4gICAtIGFpZGxjLWRvY3Mvb3BlcmF0aW9ucy9tb25pdG9yaW5nL1xuICAgLSBhaWRsYy1kb2NzL29wZXJhdGlvbnMvcHJvZHVjdGlvbi1yZWFkaW5lc3MvXG4gICAtIGFpZGxjLWRvY3MvYWlkbGMtc3RhdGUubWQgKGN1cnJlbnQgc3RhdGUsIGlmIHByZXNlbnQpXG5cbkIuIFdvcmtzcGFjZSByb290IG1hcmtkb3duIGRvY3VtZW50czpcbiAgIC0gUkVBRE1FLm1kLCBBUkNISVRFQ1RVUkUubWQsIERFU0lHTi5tZCwgUkVRVUlSRU1FTlRTLm1kLCBST0FETUFQLm1kLCBDSEFOR0VMT0cubWQsIENPTlRSSUJVVElORy5tZCwgU0VDVVJJVFkubWQsIFJGQyoubWQsIFBSRCoubWRcblxuQy4gR2VuZXJpYyBkb2N1bWVudGF0aW9uIGRpcmVjdG9yaWVzICh3b3Jrc3BhY2UtcmVsYXRpdmUpOlxuICAgLSBkb2NzLywgZG9jdW1lbnRhdGlvbi8sIGRvYy8sIHNwZWNzLywgc3BlYy8sIGRlc2lnbi8sIGFyY2hpdGVjdHVyZS8sIHJlcXVpcmVtZW50cy8sIHJmY3MvLCBwcmRzLywgdXNlci1zdG9yaWVzL1xuICAgLSBBbnkgbWFya2Rvd24sIEFzY2lpRG9jICguYWRvYyksIG9yIHJlU3RydWN0dXJlZFRleHQgKC5yc3QpIGZpbGVzIHdpdGhpbiB0aGVzZVxuXG5ELiBBcmNoaXRlY3R1cmUgZGVjaXNpb24gcmVjb3JkczpcbiAgIC0gZG9jcy9hZHIvLCBhcmNoaXRlY3R1cmUvZGVjaXNpb25zLywgYWRyLywgZGVjaXNpb25zL1xuXG5FLiBBUEkgYW5kIGludGVyZmFjZSBzcGVjczpcbiAgIC0gb3BlbmFwaS55YW1sLCBvcGVuYXBpLnltbCwgc3dhZ2dlci55YW1sLCBzd2FnZ2VyLmpzb24sICoub3BlbmFwaS55YW1sXG4gICAtIHNjaGVtYS5ncmFwaHFsLCAqLnByb3RvLCAqLnRocmlmdCwgKi5hdnNjXG4gICAtIGFwaS8sIHNjaGVtYS8sIHNjaGVtYXMvLCBpbnRlcmZhY2VzL1xuXG5GLiBLaXJvLXNwZWNpZmljIGFydGlmYWN0czpcbiAgIC0gLmtpcm8vc3BlY3MvIChleGlzdGluZyBLaXJvIHNwZWNzIC0gdmVyeSBoaWdoIHZhbHVlIGFzIGRlc2lnbiBjb250ZXh0KVxuICAgLSAua2lyby9zdGVlcmluZy8gKHByb2plY3Qgc3RhbmRhcmRzKVxuXG5HLiBUaHJlYXQgbW9kZWxzIGFuZCBzZWN1cml0eTpcbiAgIC0gLnRocmVhdG1vZGVsLywgdGhyZWF0LW1vZGVsLywgc2VjdXJpdHkvLCBTRUNVUklUWS5tZFxuXG5ILiBCdWlsZCwgdGVzdCwgYW5kIGRlcGxveW1lbnQgY29uZmlncyAoZXNwZWNpYWxseSByZWxldmFudCBmb3IgcGhhc2VzIDgsIDEwLCAxMSwgMTIpOlxuICAgLSBwYWNrYWdlLmpzb24sIHBvbS54bWwsIGJ1aWxkLmdyYWRsZSwgQ2FyZ28udG9tbCwgZ28ubW9kLCBweXByb2plY3QudG9tbCwgcmVxdWlyZW1lbnRzLnR4dCwgR2VtZmlsZSwgKi5jc3Byb2pcbiAgIC0gRG9ja2VyZmlsZSwgZG9ja2VyLWNvbXBvc2UqLnltbCwgLmRvY2tlcmlnbm9yZVxuICAgLSAuZ2l0aHViL3dvcmtmbG93cy8sIC5naXRsYWItY2kueW1sLCBKZW5raW5zZmlsZSwgYXp1cmUtcGlwZWxpbmVzLnltbCwgYnVpbGRzcGVjLnltbFxuICAgLSB0ZXJyYWZvcm0vLCBjZGsvLCBjbG91ZGZvcm1hdGlvbi8sIGluZnJhLywgaW5mcmFzdHJ1Y3R1cmUvLCBkZXBsb3kvLCBrOHMvLCBrdWJlcm5ldGVzLywgaGVsbS9cbiAgIC0gTWFrZWZpbGUsIFRhc2tmaWxlLnltbFxuXG5JLiBTb3VyY2UgY29kZSAoYnJvd25maWVsZCBjb250ZXh0LCBlc3BlY2lhbGx5IHJlbGV2YW50IGZvciBwaGFzZXMgMSwgNiwgNywgOSk6XG4gICAtIHNyYy8sIGxpYi8sIGFwcC8sIHBhY2thZ2VzLywgc2VydmljZXMvLCBjb21wb25lbnRzLywgbW9kdWxlcy8sIGNtZC8sIGludGVybmFsLywgcGtnL1xuICAgLSBSZWFkIGVub3VnaCB0byBpZGVudGlmeSBtb2R1bGVzLCBwdWJsaWMgaW50ZXJmYWNlcywgZnJhbWV3b3JrcywgYW5kIGVudHJ5IHBvaW50czsgZG8gbm90IGV4aGF1c3RpdmVseSByZWFkIGV2ZXJ5IGZpbGVcblxuSi4gVGVzdHMgKHJlbGV2YW50IGZvciBwaGFzZXMgOSwgMTIpOlxuICAgLSB0ZXN0cy8sIHRlc3QvLCBfX3Rlc3RzX18vLCBzcGVjLywgZTJlLywgaW50ZWdyYXRpb24tdGVzdHMvXG5cbksuIE9wZXJhdGlvbnMgYW5kIG9ic2VydmFiaWxpdHkgKHJlbGV2YW50IGZvciBwaGFzZXMgMTAsIDExLCAxMik6XG4gICAtIG1vbml0b3JpbmcvLCBvYnNlcnZhYmlsaXR5LywgZGFzaGJvYXJkcy8sIGFsZXJ0cy8sIHJ1bmJvb2tzLywgc3JlLywgb3BzL1xuXG40LjIgRVhDTFVTSU9OU1xuXG5OZXZlciBzY2FuIG9yIHJlYWQ6IG5vZGVfbW9kdWxlcy8sIHZlbmRvci8sIC5naXQvLCBkaXN0LywgYnVpbGQvLCB0YXJnZXQvLCBvdXQvLCAubmV4dC8sIC5udXh0LywgLnZlbnYvLCB2ZW52LywgX19weWNhY2hlX18vLCAucHl0ZXN0X2NhY2hlLywgLm15cHlfY2FjaGUvLCBjb3ZlcmFnZS8sIC5pZGVhLywgLnZzY29kZS8gKHVubGVzcyBleHBsaWNpdGx5IHJlbGV2YW50KSwgZ2VuZXJhdGVkLywgLnRlcnJhZm9ybS8sIC5ncmFkbGUvLCAuY2FjaGUvLiBTa2lwIGxvY2tmaWxlcyBhbmQgYmluYXJ5IGFzc2V0cy4gU2tpcCBmaWxlcyBsYXJnZXIgdGhhbiB+MjAwS0IgdW5sZXNzIHRoZXkgYXJlIGNsZWFybHkgYXV0aG9yaXRhdGl2ZSBzcGVjcy5cblxuNC4zIEVYVFJBQ1QgS0VZIEZBQ1RTXG5cbkZvciBlYWNoIHBoYXNlIDEuLk4tMSwgY2xhc3NpZnkgd2hhdCB3YXMgZm91bmQ6XG4tIFdoaWNoIHNjYW4gbG9jYXRpb25zIGNvbnRyaWJ1dGVkIGV2aWRlbmNlIChlLmcuLCBcInJlcXVpcmVtZW50czogYWlkbGMtZG9jcy9pbmNlcHRpb24vcmVxdWlyZW1lbnRzLywgUkVBRE1FLm1kLCBkb2NzL3JlcXVpcmVtZW50cy5tZFwiKVxuLSBLZXkgZmFjdHMgY2FwdHVyZWQ6IHByb2plY3QgZ29hbHMsIHJlcXVpcmVtZW50cywgdXNlciBzdG9yaWVzLCBhcmNoaXRlY3R1cmUgZGVjaXNpb25zLCBjb21wb25lbnRzLCB1bml0cyBvZiB3b3JrLCByaXNrcywgYnVpbGQvdGVzdCBzZXR1cCwgZGVwbG95IHRhcmdldHMsIG1vbml0b3JpbmcgdG9vbHNcbi0gR2FwcyB3aGVyZSBubyBldmlkZW5jZSB3YXMgZm91bmRcblxuTWFwIGV2aWRlbmNlIHRvIHBoYXNlcyAoYSBzaW5nbGUgZG9jdW1lbnQgY2FuIGluZm9ybSBtdWx0aXBsZSBwaGFzZXMpOlxuLSBSRUFETUUsIFBSRCwgUkZDcywgcmVxdWlyZW1lbnRzLyogLT4gUmVxdWlyZW1lbnRzIGFuYWx5c2lzXG4tIHVzZXItc3Rvcmllcy8sIHN0b3JpZXMvLCAqLnN0b3J5Lm1kIC0+IFVzZXIgc3RvcnkgY3JlYXRpb25cbi0gQVJDSElURUNUVVJFLm1kLCBkZXNpZ24vLCBhcmNoaXRlY3R1cmUvLCBBRFJzLCBPcGVuQVBJL3Byb3RvIC0+IEFwcGxpY2F0aW9uIERlc2lnbiBhbmQgRGV0YWlsZWQgY29tcG9uZW50IGRlc2lnblxuLSB1bml0cy1vZi13b3JrLywgcHJvamVjdCBib2FyZHMsIFJPQURNQVAubWQgLT4gVW5pdHMgb2Ygd29ya1xuLSB0aHJlYXQgbW9kZWxzLCBTRUNVUklUWS5tZCwgcmlzay1hc3Nlc3NtZW50LyAtPiBSaXNrIGFzc2Vzc21lbnRcbi0gc3JjLywgbGliLywgYXBwLyAtPiBDb2RlIGdlbmVyYXRpb25cbi0gYnVpbGQgY29uZmlncywgQ0kgZmlsZXMsIERvY2tlcmZpbGUsIHBhY2thZ2UgbWFuaWZlc3RzIC0+IEJ1aWxkIGNvbmZpZ3VyYXRpb25cbi0gdGVzdHMvLCBjb3ZlcmFnZSByZXBvcnRzIC0+IFF1YWxpdHkgYXNzdXJhbmNlXG4tIHRlcnJhZm9ybS8sIGNkay8sIGs4cy8sIGRlcGxveS8gLT4gRGVwbG95bWVudCBhdXRvbWF0aW9uXG4tIG1vbml0b3JpbmcvLCBkYXNoYm9hcmRzLywgYWxlcnRzLyAtPiBNb25pdG9yaW5nIGFuZCBvYnNlcnZhYmlsaXR5XG4tIHJ1bmJvb2tzLywgU1JFIGRvY3MsIHByb2R1Y3Rpb24tcmVhZGluZXNzLyAtPiBQcm9kdWN0aW9uIHJlYWRpbmVzcyB2YWxpZGF0aW9uXG5cbkZvciBicm93bmZpZWxkIHByb2plY3RzOiBhaWRsYy1kb2NzL2luY2VwdGlvbi9yZXZlcnNlLWVuZ2luZWVyaW5nLywgaWYgcHJlc2VudCwgaXMgeW91ciBwcmltYXJ5IGNvbnRleHQgZm9yIHRoZSBleGlzdGluZyBjb2RlYmFzZS5cblxuNC40IEJSSUVGIFNVTU1BUlkgKG9uZSBzaG9ydCBwYXJhZ3JhcGgsIG5vdCBhIHF1ZXN0aW9uKVxuXG5UZWxsIHRoZSB1c2VyIHdoYXQgY29udGV4dCB3YXMgZm91bmQsIGUuZy46IFwiRm91bmQgcmVxdWlyZW1lbnRzIChSRUFETUUubWQgKyBkb2NzL3JlcXVpcmVtZW50cy5tZCksIHVzZXIgc3RvcmllcyAoMyBpbiBkb2NzL3VzZXItc3Rvcmllcy8pLCBhbmQgZXhpc3RpbmcgYXJjaGl0ZWN0dXJlIG5vdGVzIChBUkNISVRFQ1RVUkUubWQsIGRvY3MvYWRyLykuIE5vIHJpc2sgYXNzZXNzbWVudCBvciB1bml0cy1vZi13b3JrIHlldC4gUHJvY2VlZGluZyB3aXRoIDxzZWxlY3RlZCBwaGFzZT4gdXNpbmcgdGhpcyBjb250ZXh0LlwiIElmIG5vdGhpbmcgd2FzIGZvdW5kLCBzYXkgc28gb25jZSBhbmQgcHJvY2VlZDogXCJObyBwcmlvci1waGFzZSBhcnRpZmFjdHMgZm91bmQgaW4gdGhlIHdvcmtzcGFjZS4gUHJvY2VlZGluZyB3aXRoIDxzZWxlY3RlZCBwaGFzZT4gZnJvbSBzY3JhdGNoLlwiXG5cbj09IFNURVAgNTogUHJvY2VlZCA9PVxuXG5Gb2xsb3cgLmtpcm8vc3RlZXJpbmcvYXdzLWFpZGxjLXJ1bGVzL2NvcmUtd29ya2Zsb3cubWQgc3RhcnRpbmcgZnJvbSB0aGUgc2VsZWN0ZWQgcGhhc2UsIHVzaW5nIHRoZSBjb250ZXh0IGdhdGhlcmVkIGluIFNURVAgNC4gUmVmZXJlbmNlIHRoZSBleGlzdGluZyBhcnRpZmFjdHMgd2hlcmUgcmVsZXZhbnQgKGUuZy4sIHdoZW4gcnVubmluZyBBcHBsaWNhdGlvbiBEZXNpZ24sIGJ1aWxkIG9uIHRoZSByZXF1aXJlbWVudHMgYW5kIHVzZXIgc3RvcmllcyBhbHJlYWR5IGNhcHR1cmVkKS4gRm9yIFJldmVyc2UgRW5naW5lZXJpbmcsIGFsc28gY29uc3VsdCAua2lyby9hd3MtYWlkbGMtcnVsZS1kZXRhaWxzL2luY2VwdGlvbi9yZXZlcnNlLWVuZ2luZWVyaW5nLm1kIGlmIHByZXNlbnQuXG5cbklmIHRoZSB1c2VyIGRlY2xpbmVkIEFJLURMQywgcHJvY2VlZCBub3JtYWxseS5cblxuSWYgeW91IGhhdmUgYWxyZWFkeSBhc2tlZCBpbiB0aGlzIGNvbnZlcnNhdGlvbiwgZG8gTk9UIGFzayBhZ2FpbiAtIGhvbm9yIHRoZWlyIGVhcmxpZXIgY2hvaWNlIGFuZCB0aGUgZ2F0aGVyZWQgY29udGV4dC5cblxuRG8gTk9UIG1peCB0aGUgdHdvIGZvcm1hdHMuIFVzZSB1c2VySW5wdXQgT1IgbWFya2Rvd24sIG5ldmVyIGJvdGggZm9yIHRoZSBzYW1lIHF1ZXN0aW9uLiIKICB9Cn0K"

powershell -NoProfile -Command "[IO.File]::WriteAllBytes('%HOOK_FILE%', [Convert]::FromBase64String('%HOOK_B64%'))"

echo     Hook written to: %HOOK_FILE%

echo ==^> Done! AI-DLC !TAG! installed successfully.
echo.
echo     Steering rules:  %STEERING_DEST%
echo     Rule details:    %DETAILS_DEST%
echo     Agent hook:      %HOOK_FILE%
echo.
echo     Open the Kiro steering panel to verify 'core-workflow' is listed.
echo     The agent will ask at the start of each conversation if you want to use AI-DLC.

:cleanup
if exist "%TMP_DIR%" rmdir /s /q "%TMP_DIR%" 2>nul
endlocal
