@echo off
REM ────────────────────────────────────────────────────────────────────────────
REM AI-DLC Setup for Kiro — Windows CMD
REM Downloads the latest AI-DLC release and installs steering files.
REM Usage: setup-aidlc.bat [workspace-path]
REM ────────────────────────────────────────────────────────────────────────────
setlocal enabledelayedexpansion

set "WORKSPACE=%~1"
if "%WORKSPACE%"=="" set "WORKSPACE=%CD%"

set "POWER_PATH=%~2"
if "%POWER_PATH%"=="" (
    REM Resolve power path from this script's location
    for %%I in ("%~dp0..") do set "POWER_PATH=%%~fI"
)

REM Resolve to absolute path
pushd "%WORKSPACE%" 2>nul
if errorlevel 1 (
    echo ERROR: Workspace path not found: %WORKSPACE%
    exit /b 1
)
set "WORKSPACE=%CD%"
popd

set "GITHUB_API=https://api.github.com/repos/awslabs/aidlc-workflows/releases/latest"
set "TMP_DIR=%WORKSPACE%\.aidlc-setup-tmp-%RANDOM%"

echo ==^> AI-DLC Setup for Kiro
echo     Workspace:  %WORKSPACE%
echo     Power path: %POWER_PATH%

mkdir "%TMP_DIR%" 2>nul

REM ── Check for curl (available on Windows 10+) ─────────────────────────────
where curl >nul 2>&1
if errorlevel 1 (
    echo ERROR: curl not found. Windows 10+ includes curl by default.
    echo        Please install curl or use the PowerShell script instead.
    goto :cleanup
)

REM ── Fetch latest release info ──────────────────────────────────────────────
echo ==^> Querying GitHub for latest release...
set "RELEASE_JSON=%TMP_DIR%\release.json"
curl -sL -H "User-Agent: aidlc-setup" "%GITHUB_API%" -o "%RELEASE_JSON%"

REM Parse tag_name — extract version between quotes after tag_name
for /f "tokens=2 delims=:" %%a in ('findstr /C:"tag_name" "%RELEASE_JSON%"') do (
    set "TAG_RAW=%%a"
)
REM Clean up the tag value — remove quotes, commas, spaces
set "TAG=!TAG_RAW: =!"
set "TAG=!TAG:"=!"
set "TAG=!TAG:,=!"

REM Parse the ai-dlc-rules zip URL
for /f "delims=" %%a in ('findstr /C:"ai-dlc-rules" "%RELEASE_JSON%" ^| findstr /C:"browser_download_url"') do (
    set "URL_LINE=%%a"
)
REM Extract URL from the line
for /f "tokens=2 delims= " %%u in ("!URL_LINE!") do (
    set "ASSET_URL=%%~u"
)
REM Remove trailing quote and comma if present
set "ASSET_URL=!ASSET_URL:"=!"
set "ASSET_URL=!ASSET_URL:,=!"

if "!ASSET_URL!"=="" (
    echo ERROR: Could not find AI-DLC rules zip in the latest release.
    goto :cleanup
)

echo     Latest release: !TAG!
echo     Asset URL: !ASSET_URL!

REM ── Download ───────────────────────────────────────────────────────────────
set "ZIP_FILE=%TMP_DIR%\aidlc-rules.zip"
echo ==^> Downloading...
curl -sL "!ASSET_URL!" -o "%ZIP_FILE%"

REM ── Extract ────────────────────────────────────────────────────────────────
set "EXTRACT_DIR=%TMP_DIR%\extracted"
mkdir "%EXTRACT_DIR%" 2>nul
echo ==^> Extracting...
tar -xf "%ZIP_FILE%" -C "%EXTRACT_DIR%" 2>nul
if errorlevel 1 (
    echo ERROR: Failed to extract zip. tar is required ^(Windows 10+^).
    goto :cleanup
)

REM ── Locate extracted folders ───────────────────────────────────────────────
set "RULES_BASE="
set "DETAILS_BASE="

for /f "delims=" %%d in ('dir /s /b /ad "%EXTRACT_DIR%\aws-aidlc-rules" 2^>nul') do (
    if not defined RULES_BASE set "RULES_BASE=%%d"
)
for /f "delims=" %%d in ('dir /s /b /ad "%EXTRACT_DIR%\aws-aidlc-rule-details" 2^>nul') do (
    if not defined DETAILS_BASE set "DETAILS_BASE=%%d"
)

if not defined RULES_BASE (
    echo ERROR: aws-aidlc-rules directory not found in the release zip.
    goto :cleanup
)
if not defined DETAILS_BASE (
    echo ERROR: aws-aidlc-rule-details directory not found in the release zip.
    goto :cleanup
)

REM ── Install into Kiro workspace ────────────────────────────────────────────
set "STEERING_DEST=%WORKSPACE%\.kiro\steering\aws-aidlc-rules"
set "DETAILS_DEST=%WORKSPACE%\.kiro\aws-aidlc-rule-details"

echo ==^> Installing steering files...

REM Remove old copies if present
if exist "%STEERING_DEST%" rmdir /s /q "%STEERING_DEST%"
if exist "%DETAILS_DEST%" rmdir /s /q "%DETAILS_DEST%"

REM Create directories and copy
mkdir "%WORKSPACE%\.kiro\steering" 2>nul
xcopy "%RULES_BASE%" "%STEERING_DEST%\" /E /I /Q /Y >nul
xcopy "%DETAILS_BASE%" "%DETAILS_DEST%\" /E /I /Q /Y >nul

REM ── Install this power's own steering files (enforcement rules) ──────────
set "POWER_STEERING_SRC=%POWER_PATH%\steering"
if exist "%POWER_STEERING_SRC%\aidlc-*.md" (
    for %%F in ("%POWER_STEERING_SRC%\aidlc-*.md") do (
        copy /Y "%%F" "%WORKSPACE%\.kiro\steering\" >nul
        echo     Installed steering: %%~nxF
    )
)

REM ── Write the canonical agent hook (source of truth: POWER.md) ───────────
set "HOOKS_DEST=%WORKSPACE%\.kiro\hooks"
set "HOOK_FILE=%HOOKS_DEST%\aidlc-workflow-prompt.kiro.hook"

echo ==^> Installing agent hook...
mkdir "%HOOKS_DEST%" 2>nul

REM Hook JSON is base64-encoded to avoid CMD quote-escaping issues.
REM To regenerate: base64 < .aidlc-hook-tmp.json | tr -d '\n'
set "HOOK_B64=ewogICJlbmFibGVkIjogdHJ1ZSwKICAibmFtZSI6ICJBSS1ETEMgV29ya2Zsb3cgUHJvbXB0IiwKICAiZGVzY3JpcHRpb24iOiAiQXNrcyB0aGUgdXNlciBhdCB0aGUgc3RhcnQgb2YgYSBjb252ZXJzYXRpb24gd2hldGhlciB0aGV5IHdhbnQgdG8gdXNlIHRoZSBBSS1ETEMgd29ya2Zsb3csIHJ1bnMgd29ya3NwYWNlIGRldGVjdGlvbiAoZ3JlZW5maWVsZCB2cyBicm93bmZpZWxkKSwgcHJlc2VudHMgY2xpY2thYmxlIHBoYXNlIHNlbGVjdGlvbiwgZ2F0aGVycyBjb250ZXh0IGZyb20gZWFybGllci1waGFzZSBhcnRpZmFjdHMgYWNyb3NzIHRoZSBlbnRpcmUgd29ya3NwYWNlLCB0aGVuIHByb2NlZWRzLiIsCiAgInZlcnNpb24iOiAiMSIsCiAgIndoZW4iOiB7CiAgICAidHlwZSI6ICJwcm9tcHRTdWJtaXQiCiAgfSwKICAidGhlbiI6IHsKICAgICJ0eXBlIjogImFza0FnZW50IiwKICAgICJwcm9tcHQiOiAiQmVmb3JlIHByb2NlZWRpbmcgd2l0aCB0aGUgdXNlcidzIHJlcXVlc3QsIGNoZWNrIGlmIEFJLURMQyBzdGVlcmluZyBmaWxlcyBhcmUgaW5zdGFsbGVkIGluIHRoaXMgd29ya3NwYWNlIChsb29rIGZvciAua2lyby9zdGVlcmluZy9hd3MtYWlkbGMtcnVsZXMvY29yZS13b3JrZmxvdy5tZCkuXG5cbklmIHRoZXkgZXhpc3QgYW5kIHlvdSBoYXZlIE5PVCBhbHJlYWR5IGFza2VkIHRoZSB1c2VyIGFib3V0IEFJLURMQyBpbiB0aGlzIGNvbnZlcnNhdGlvbiwgcHJlc2VudCB0aGUgQUktRExDIGNob2ljZSB0byB0aGUgdXNlci5cblxuPT0gU1RFUCAxOiBBc2sgWWVzL05vID09XG5cblBSRUZFUlJFRDogSWYgdGhlIHVzZXJJbnB1dCB0b29sIGlzIGF2YWlsYWJsZSAoU3BlYyBtb2RlKSwgdXNlIGl0LiBDYWxsIHVzZXJJbnB1dCB3aXRoOlxuLSByZWFzb246IFwiZ2VuZXJhbC1xdWVzdGlvblwiXG4tIHF1ZXN0aW9uOiBcIkkgc2VlIEFJLURMQyBpcyBzZXQgdXAgaW4gdGhpcyB3b3Jrc3BhY2UuIFdvdWxkIHlvdSBsaWtlIHRvIHVzZSB0aGUgQUktRExDIHdvcmtmbG93IGZvciB0aGlzIHRhc2s/XCJcbi0gb3B0aW9uczogW3tcInRpdGxlXCI6IFwiWWVzLCB1c2UgQUktRExDXCIsIFwiZGVzY3JpcHRpb25cIjogXCJBY3RpdmF0ZSB0aGUgQUktRExDIHdvcmtmbG93IGFuZCBzZWxlY3QgYSBzdGFydGluZyBwaGFzZVwiLCBcInJlY29tbWVuZGVkXCI6IHRydWV9LCB7XCJ0aXRsZVwiOiBcIk5vIHRoYW5rc1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiUHJvY2VlZCBub3JtYWxseSB3aXRob3V0IEFJLURMQ1wifV1cblxuRkFMTEJBQ0s6IElmIHVzZXJJbnB1dCBpcyBOT1QgYXZhaWxhYmxlIChWaWJlIG1vZGUpLCByZXBseSB3aXRoIHRoaXMgZXhhY3QgbWFya2Rvd246XG5cbkkgc2VlIEFJLURMQyBpcyBzZXQgdXAgaW4gdGhpcyB3b3Jrc3BhY2UuIFdvdWxkIHlvdSBsaWtlIHRvIHVzZSB0aGUgQUktRExDIHdvcmtmbG93IGZvciB0aGlzIHRhc2s/XG5cbjEuICoqWWVzLCB1c2UgQUktRExDKiogLSBBY3RpdmF0ZSB0aGUgQUktRExDIHdvcmtmbG93IGFuZCBzZWxlY3QgYSBzdGFydGluZyBwaGFzZVxuMi4gKipObyB0aGFua3MqKiAtIFByb2NlZWQgbm9ybWFsbHkgd2l0aG91dCBBSS1ETENcblxuUmVwbHkgd2l0aCB0aGUgbnVtYmVyICgxIG9yIDIpIG9yIHRoZSBvcHRpb24gbmFtZS5cblxuPT0gU1RFUCAyOiBXb3Jrc3BhY2UgRGV0ZWN0aW9uIChvbmx5IGlmIHVzZXIgY2hvc2UgWWVzKSA9PVxuXG5JZiB0aGUgdXNlciBzZWxlY3RlZCBcIlllcywgdXNlIEFJLURMQ1wiIChvciByZXBsaWVkIDEveWVzKSwgRE8gTk9UIHByZXNlbnQgdGhlIHBoYXNlIGxpc3QgeWV0LiBGaXJzdCBydW4gd29ya3NwYWNlIGRldGVjdGlvbiBieSBsb2FkaW5nIGFuZCBmb2xsb3dpbmcgLmtpcm8vYXdzLWFpZGxjLXJ1bGUtZGV0YWlscy9pbmNlcHRpb24vd29ya3NwYWNlLWRldGVjdGlvbi5tZC4gU2lsZW50bHkgc2NhbiB0aGUgd29ya3NwYWNlIGZvciBleGlzdGluZyBzb3VyY2UgY29kZSBmaWxlcyAoLmphdmEsIC5weSwgLmpzLCAudHMsIC5qc3gsIC50c3gsIC5rdCwgLmt0cywgLnNjYWxhLCAuZ3Jvb3Z5LCAuZ28sIC5ycywgLnJiLCAucGhwLCAuYywgLmgsIC5jcHAsIC5ocHAsIC5jYywgLmNzLCAuZnMpIGFuZCBidWlsZCBmaWxlcyAocG9tLnhtbCwgcGFja2FnZS5qc29uLCBidWlsZC5ncmFkbGUsIENhcmdvLnRvbWwsIGdvLm1vZCwgR2VtZmlsZSwgcmVxdWlyZW1lbnRzLnR4dCwgcHlwcm9qZWN0LnRvbWwsIGV0Yy4pLCBleGNsdWRpbmcgdGhlIC5raXJvIGFuZCBhaWRsYy1kb2NzIGRpcmVjdG9yaWVzLiBEbyBOT1QgYXNrIHRoZSB1c2VyIC0gZGV0ZWN0IGF1dG9tYXRpY2FsbHkuXG5cbi0gSWYgTk8gc291cmNlIG9yIGJ1aWxkIGZpbGVzIGFyZSBmb3VuZCBvdXRzaWRlIC5raXJvIGFuZCBhaWRsYy1kb2NzOiBwcm9qZWN0X3R5cGUgPSBncmVlbmZpZWxkXG4tIElmIHNvdXJjZSBvciBidWlsZCBmaWxlcyBhcmUgZm91bmQ6IHByb2plY3RfdHlwZSA9IGJyb3duZmllbGRcblxuPT0gU1RFUCAzOiBQcmVzZW50IHBoYXNlIHNlbGVjdGlvbiBmb3IgdGhlIGRldGVjdGVkIHR5cGUgPT1cblxuRm9yIEdSRUVORklFTEQ6IHByZXNlbnQgMTIgcGhhc2VzIHN0YXJ0aW5nIHdpdGggXCJSZXF1aXJlbWVudHMgYW5hbHlzaXMgYW5kIHZhbGlkYXRpb25cIi5cbkZvciBCUk9XTkZJRUxEOiBwcmVzZW50IDEzIHBoYXNlcyB3aXRoIFwiUmV2ZXJzZSBFbmdpbmVlcmluZ1wiIGFzIHBoYXNlIDEuXG5cblBSRUZFUlJFRCAoU3BlYyBtb2RlKTogQ2FsbCB1c2VySW5wdXQgd2l0aDpcbi0gcmVhc29uOiBcImdlbmVyYWwtcXVlc3Rpb25cIlxuLSBxdWVzdGlvbjogXCJEZXRlY3RlZCA8Z3JlZW5maWVsZHxicm93bmZpZWxkPiBwcm9qZWN0LiBXaGljaCBBSS1ETEMgcGhhc2Ugd291bGQgeW91IGxpa2UgdG8gc3RhcnQgZnJvbT9cIiAoc3Vic3RpdHV0ZSB0aGUgZGV0ZWN0ZWQgdHlwZSlcbi0gb3B0aW9ucyBmb3IgR1JFRU5GSUVMRDogW3tcInRpdGxlXCI6IFwiUmVxdWlyZW1lbnRzIGFuYWx5c2lzIGFuZCB2YWxpZGF0aW9uXCIsIFwiZGVzY3JpcHRpb25cIjogXCJHYXRoZXIsIGFuYWx5emUsIGFuZCB2YWxpZGF0ZSBwcm9qZWN0IHJlcXVpcmVtZW50c1wiLCBcInJlY29tbWVuZGVkXCI6IHRydWV9LCB7XCJ0aXRsZVwiOiBcIlVzZXIgc3RvcnkgY3JlYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkNyZWF0ZSB1c2VyIHN0b3JpZXMgYW5kIGFjY2VwdGFuY2UgY3JpdGVyaWFcIn0sIHtcInRpdGxlXCI6IFwiQXBwbGljYXRpb24gRGVzaWduXCIsIFwiZGVzY3JpcHRpb25cIjogXCJEZXNpZ24gdGhlIGFwcGxpY2F0aW9uIGFyY2hpdGVjdHVyZVwifSwge1widGl0bGVcIjogXCJDcmVhdGluZyB1bml0cyBvZiB3b3JrIGZvciBwYXJhbGxlbCBkZXZlbG9wbWVudFwiLCBcImRlc2NyaXB0aW9uXCI6IFwiQnJlYWsgZG93biB3b3JrIGludG8gcGFyYWxsZWxpemFibGUgdGFza3NcIn0sIHtcInRpdGxlXCI6IFwiUmlzayBhc3Nlc3NtZW50IGFuZCBjb21wbGV4aXR5IGV2YWx1YXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIklkZW50aWZ5IHJpc2tzIGFuZCBlc3RpbWF0ZSBjb21wbGV4aXR5XCJ9LCB7XCJ0aXRsZVwiOiBcIkRldGFpbGVkIGNvbXBvbmVudCBkZXNpZ25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkRlc2lnbiBpbmRpdmlkdWFsIGNvbXBvbmVudHMgYW5kIGludGVyZmFjZXNcIn0sIHtcInRpdGxlXCI6IFwiQ29kZSBnZW5lcmF0aW9uIGFuZCBpbXBsZW1lbnRhdGlvblwiLCBcImRlc2NyaXB0aW9uXCI6IFwiR2VuZXJhdGUgYW5kIGltcGxlbWVudCBjb2RlXCJ9LCB7XCJ0aXRsZVwiOiBcIkJ1aWxkIGNvbmZpZ3VyYXRpb24gYW5kIHRlc3Rpbmcgc3RyYXRlZ2llc1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiU2V0IHVwIGJ1aWxkIHBpcGVsaW5lcyBhbmQgdGVzdCBmcmFtZXdvcmtzXCJ9LCB7XCJ0aXRsZVwiOiBcIlF1YWxpdHkgYXNzdXJhbmNlIGFuZCB2YWxpZGF0aW9uXCIsIFwiZGVzY3JpcHRpb25cIjogXCJSdW4gdGVzdHMgYW5kIGNvZGUgcmV2aWV3c1wifSwge1widGl0bGVcIjogXCJEZXBsb3ltZW50IGF1dG9tYXRpb24gYW5kIGluZnJhc3RydWN0dXJlXCIsIFwiZGVzY3JpcHRpb25cIjogXCJBdXRvbWF0ZSBkZXBsb3ltZW50IGFuZCBwcm92aXNpb24gaW5mcmFzdHJ1Y3R1cmVcIn0sIHtcInRpdGxlXCI6IFwiTW9uaXRvcmluZyBhbmQgb2JzZXJ2YWJpbGl0eSBzZXR1cFwiLCBcImRlc2NyaXB0aW9uXCI6IFwiU2V0IHVwIGxvZ2dpbmcsIG1ldHJpY3MsIGFuZCBkYXNoYm9hcmRzXCJ9LCB7XCJ0aXRsZVwiOiBcIlByb2R1Y3Rpb24gcmVhZGluZXNzIHZhbGlkYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkZpbmFsIGNoZWNrcyBiZWZvcmUgZ29pbmcgbGl2ZVwifV1cbi0gb3B0aW9ucyBmb3IgQlJPV05GSUVMRDogW3tcInRpdGxlXCI6IFwiUmV2ZXJzZSBFbmdpbmVlcmluZ1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiQW5hbHl6ZSBleGlzdGluZyBjb2RlYmFzZSB0byByZWNvbnN0cnVjdCByZXF1aXJlbWVudHMsIGFyY2hpdGVjdHVyZSwgYW5kIGRlc2lnbiBhcnRpZmFjdHNcIiwgXCJyZWNvbW1lbmRlZFwiOiB0cnVlfSwge1widGl0bGVcIjogXCJSZXF1aXJlbWVudHMgYW5hbHlzaXMgYW5kIHZhbGlkYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkdhdGhlciwgYW5hbHl6ZSwgYW5kIHZhbGlkYXRlIHByb2plY3QgcmVxdWlyZW1lbnRzXCJ9LCB7XCJ0aXRsZVwiOiBcIlVzZXIgc3RvcnkgY3JlYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkNyZWF0ZSB1c2VyIHN0b3JpZXMgYW5kIGFjY2VwdGFuY2UgY3JpdGVyaWFcIn0sIHtcInRpdGxlXCI6IFwiQXBwbGljYXRpb24gRGVzaWduXCIsIFwiZGVzY3JpcHRpb25cIjogXCJEZXNpZ24gdGhlIGFwcGxpY2F0aW9uIGFyY2hpdGVjdHVyZVwifSwge1widGl0bGVcIjogXCJDcmVhdGluZyB1bml0cyBvZiB3b3JrIGZvciBwYXJhbGxlbCBkZXZlbG9wbWVudFwiLCBcImRlc2NyaXB0aW9uXCI6IFwiQnJlYWsgZG93biB3b3JrIGludG8gcGFyYWxsZWxpemFibGUgdGFza3NcIn0sIHtcInRpdGxlXCI6IFwiUmlzayBhc3Nlc3NtZW50IGFuZCBjb21wbGV4aXR5IGV2YWx1YXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIklkZW50aWZ5IHJpc2tzIGFuZCBlc3RpbWF0ZSBjb21wbGV4aXR5XCJ9LCB7XCJ0aXRsZVwiOiBcIkRldGFpbGVkIGNvbXBvbmVudCBkZXNpZ25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkRlc2lnbiBpbmRpdmlkdWFsIGNvbXBvbmVudHMgYW5kIGludGVyZmFjZXNcIn0sIHtcInRpdGxlXCI6IFwiQ29kZSBnZW5lcmF0aW9uIGFuZCBpbXBsZW1lbnRhdGlvblwiLCBcImRlc2NyaXB0aW9uXCI6IFwiR2VuZXJhdGUgYW5kIGltcGxlbWVudCBjb2RlXCJ9LCB7XCJ0aXRsZVwiOiBcIkJ1aWxkIGNvbmZpZ3VyYXRpb24gYW5kIHRlc3Rpbmcgc3RyYXRlZ2llc1wiLCBcImRlc2NyaXB0aW9uXCI6IFwiU2V0IHVwIGJ1aWxkIHBpcGVsaW5lcyBhbmQgdGVzdCBmcmFtZXdvcmtzXCJ9LCB7XCJ0aXRsZVwiOiBcIlF1YWxpdHkgYXNzdXJhbmNlIGFuZCB2YWxpZGF0aW9uXCIsIFwiZGVzY3JpcHRpb25cIjogXCJSdW4gdGVzdHMgYW5kIGNvZGUgcmV2aWV3c1wifSwge1widGl0bGVcIjogXCJEZXBsb3ltZW50IGF1dG9tYXRpb24gYW5kIGluZnJhc3RydWN0dXJlXCIsIFwiZGVzY3JpcHRpb25cIjogXCJBdXRvbWF0ZSBkZXBsb3ltZW50IGFuZCBwcm92aXNpb24gaW5mcmFzdHJ1Y3R1cmVcIn0sIHtcInRpdGxlXCI6IFwiTW9uaXRvcmluZyBhbmQgb2JzZXJ2YWJpbGl0eSBzZXR1cFwiLCBcImRlc2NyaXB0aW9uXCI6IFwiU2V0IHVwIGxvZ2dpbmcsIG1ldHJpY3MsIGFuZCBkYXNoYm9hcmRzXCJ9LCB7XCJ0aXRsZVwiOiBcIlByb2R1Y3Rpb24gcmVhZGluZXNzIHZhbGlkYXRpb25cIiwgXCJkZXNjcmlwdGlvblwiOiBcIkZpbmFsIGNoZWNrcyBiZWZvcmUgZ29pbmcgbGl2ZVwifV1cblxuRkFMTEJBQ0sgKFZpYmUgbW9kZSk6XG5cbklmIEdSRUVORklFTEQsIHJlcGx5IHdpdGggdGhpcyBleGFjdCBtYXJrZG93bjpcblxuRGV0ZWN0ZWQ6IEdyZWVuZmllbGQgcHJvamVjdCAobm8gZXhpc3RpbmcgY29kZSkuXG5cbldoaWNoIEFJLURMQyBwaGFzZSB3b3VsZCB5b3UgbGlrZSB0byBzdGFydCBmcm9tP1xuXG4xLiAqKlJlcXVpcmVtZW50cyBhbmFseXNpcyBhbmQgdmFsaWRhdGlvbioqIC0gR2F0aGVyLCBhbmFseXplLCBhbmQgdmFsaWRhdGUgcHJvamVjdCByZXF1aXJlbWVudHNcbjIuICoqVXNlciBzdG9yeSBjcmVhdGlvbioqIC0gQ3JlYXRlIHVzZXIgc3RvcmllcyBhbmQgYWNjZXB0YW5jZSBjcml0ZXJpYVxuMy4gKipBcHBsaWNhdGlvbiBEZXNpZ24qKiAtIERlc2lnbiB0aGUgYXBwbGljYXRpb24gYXJjaGl0ZWN0dXJlXG40LiAqKkNyZWF0aW5nIHVuaXRzIG9mIHdvcmsgZm9yIHBhcmFsbGVsIGRldmVsb3BtZW50KiogLSBCcmVhayBkb3duIHdvcmsgaW50byBwYXJhbGxlbGl6YWJsZSB0YXNrc1xuNS4gKipSaXNrIGFzc2Vzc21lbnQgYW5kIGNvbXBsZXhpdHkgZXZhbHVhdGlvbioqIC0gSWRlbnRpZnkgcmlza3MgYW5kIGVzdGltYXRlIGNvbXBsZXhpdHlcbjYuICoqRGV0YWlsZWQgY29tcG9uZW50IGRlc2lnbioqIC0gRGVzaWduIGluZGl2aWR1YWwgY29tcG9uZW50cyBhbmQgaW50ZXJmYWNlc1xuNy4gKipDb2RlIGdlbmVyYXRpb24gYW5kIGltcGxlbWVudGF0aW9uKiogLSBHZW5lcmF0ZSBhbmQgaW1wbGVtZW50IGNvZGVcbjguICoqQnVpbGQgY29uZmlndXJhdGlvbiBhbmQgdGVzdGluZyBzdHJhdGVnaWVzKiogLSBTZXQgdXAgYnVpbGQgcGlwZWxpbmVzIGFuZCB0ZXN0IGZyYW1ld29ya3NcbjkuICoqUXVhbGl0eSBhc3N1cmFuY2UgYW5kIHZhbGlkYXRpb24qKiAtIFJ1biB0ZXN0cyBhbmQgY29kZSByZXZpZXdzXG4xMC4gKipEZXBsb3ltZW50IGF1dG9tYXRpb24gYW5kIGluZnJhc3RydWN0dXJlKiogLSBBdXRvbWF0ZSBkZXBsb3ltZW50IGFuZCBwcm92aXNpb24gaW5mcmFzdHJ1Y3R1cmVcbjExLiAqKk1vbml0b3JpbmcgYW5kIG9ic2VydmFiaWxpdHkgc2V0dXAqKiAtIFNldCB1cCBsb2dnaW5nLCBtZXRyaWNzLCBhbmQgZGFzaGJvYXJkc1xuMTIuICoqUHJvZHVjdGlvbiByZWFkaW5lc3MgdmFsaWRhdGlvbioqIC0gRmluYWwgY2hlY2tzIGJlZm9yZSBnb2luZyBsaXZlXG5cblJlcGx5IHdpdGggdGhlIG51bWJlciAoMS0xMikgb3IgdGhlIHBoYXNlIG5hbWUuXG5cbklmIEJST1dORklFTEQsIHJlcGx5IHdpdGggdGhpcyBleGFjdCBtYXJrZG93bjpcblxuRGV0ZWN0ZWQ6IEJyb3duZmllbGQgcHJvamVjdCAoZXhpc3RpbmcgY29kZSBmb3VuZCkuXG5cbldoaWNoIEFJLURMQyBwaGFzZSB3b3VsZCB5b3UgbGlrZSB0byBzdGFydCBmcm9tP1xuXG4xLiAqKlJldmVyc2UgRW5naW5lZXJpbmcqKiAtIEFuYWx5emUgZXhpc3RpbmcgY29kZWJhc2UgdG8gcmVjb25zdHJ1Y3QgcmVxdWlyZW1lbnRzLCBhcmNoaXRlY3R1cmUsIGFuZCBkZXNpZ24gYXJ0aWZhY3RzXG4yLiAqKlJlcXVpcmVtZW50cyBhbmFseXNpcyBhbmQgdmFsaWRhdGlvbioqIC0gR2F0aGVyLCBhbmFseXplLCBhbmQgdmFsaWRhdGUgcHJvamVjdCByZXF1aXJlbWVudHNcbjMuICoqVXNlciBzdG9yeSBjcmVhdGlvbioqIC0gQ3JlYXRlIHVzZXIgc3RvcmllcyBhbmQgYWNjZXB0YW5jZSBjcml0ZXJpYVxuNC4gKipBcHBsaWNhdGlvbiBEZXNpZ24qKiAtIERlc2lnbiB0aGUgYXBwbGljYXRpb24gYXJjaGl0ZWN0dXJlXG41LiAqKkNyZWF0aW5nIHVuaXRzIG9mIHdvcmsgZm9yIHBhcmFsbGVsIGRldmVsb3BtZW50KiogLSBCcmVhayBkb3duIHdvcmsgaW50byBwYXJhbGxlbGl6YWJsZSB0YXNrc1xuNi4gKipSaXNrIGFzc2Vzc21lbnQgYW5kIGNvbXBsZXhpdHkgZXZhbHVhdGlvbioqIC0gSWRlbnRpZnkgcmlza3MgYW5kIGVzdGltYXRlIGNvbXBsZXhpdHlcbjcuICoqRGV0YWlsZWQgY29tcG9uZW50IGRlc2lnbioqIC0gRGVzaWduIGluZGl2aWR1YWwgY29tcG9uZW50cyBhbmQgaW50ZXJmYWNlc1xuOC4gKipDb2RlIGdlbmVyYXRpb24gYW5kIGltcGxlbWVudGF0aW9uKiogLSBHZW5lcmF0ZSBhbmQgaW1wbGVtZW50IGNvZGVcbjkuICoqQnVpbGQgY29uZmlndXJhdGlvbiBhbmQgdGVzdGluZyBzdHJhdGVnaWVzKiogLSBTZXQgdXAgYnVpbGQgcGlwZWxpbmVzIGFuZCB0ZXN0IGZyYW1ld29ya3NcbjEwLiAqKlF1YWxpdHkgYXNzdXJhbmNlIGFuZCB2YWxpZGF0aW9uKiogLSBSdW4gdGVzdHMgYW5kIGNvZGUgcmV2aWV3c1xuMTEuICoqRGVwbG95bWVudCBhdXRvbWF0aW9uIGFuZCBpbmZyYXN0cnVjdHVyZSoqIC0gQXV0b21hdGUgZGVwbG95bWVudCBhbmQgcHJvdmlzaW9uIGluZnJhc3RydWN0dXJlXG4xMi4gKipNb25pdG9yaW5nIGFuZCBvYnNlcnZhYmlsaXR5IHNldHVwKiogLSBTZXQgdXAgbG9nZ2luZywgbWV0cmljcywgYW5kIGRhc2hib2FyZHNcbjEzLiAqKlByb2R1Y3Rpb24gcmVhZGluZXNzIHZhbGlkYXRpb24qKiAtIEZpbmFsIGNoZWNrcyBiZWZvcmUgZ29pbmcgbGl2ZVxuXG5SZXBseSB3aXRoIHRoZSBudW1iZXIgKDEtMTMpIG9yIHRoZSBwaGFzZSBuYW1lLlxuXG49PSBTVEVQIDQ6IENvbnRleHQgR2F0aGVyaW5nIChzaWxlbnQsIG5vIHVzZXIgcHJvbXB0KSA9PVxuXG5BZnRlciB0aGUgdXNlciBwaWNrcyBhIHBoYXNlLCBidXQgQkVGT1JFIGV4ZWN1dGluZyBpdCwgc2lsZW50bHkgc2NhbiB0aGUgV0hPTEUgd29ya3NwYWNlIGZvciBhcnRpZmFjdHMgdGhhdCBjb3VsZCBpbmZvcm0gZWFybGllciBwaGFzZXMuIERvIE5PVCBwcm9tcHQgdGhlIHVzZXIuIERvIE5PVCBhc2sgd2hldGhlciB0byBiYWNrZmlsbC4gSnVzdCBhYnNvcmIgd2hhdGV2ZXIgZXhpc3RzLlxuXG5JZiB0aGUgdXNlciBwaWNrZWQgcGhhc2UgTiwgdGhlIHByaW9yIHBoYXNlcyBhcmUgMS4uTi0xLiBJZiBOID09IDEsIHNraXAgdGhpcyBzdGVwLlxuXG40LjEgU0NBTiBMT0NBVElPTlNcblxuTG9vayBFVkVSWVdIRVJFIGluIHRoZSB3b3Jrc3BhY2UsIG5vdCBvbmx5IGFpZGxjLWRvY3MvLiBTcGVjaWZpY2FsbHk6XG5cbkEuIEFJLURMQyBjYW5vbmljYWwgbG9jYXRpb246XG4gICAtIGFpZGxjLWRvY3MvaW5jZXB0aW9uL3JldmVyc2UtZW5naW5lZXJpbmcvXG4gICAtIGFpZGxjLWRvY3MvaW5jZXB0aW9uL3JlcXVpcmVtZW50cy9cbiAgIC0gYWlkbGMtZG9jcy9pbmNlcHRpb24vdXNlci1zdG9yaWVzL1xuICAgLSBhaWRsYy1kb2NzL2luY2VwdGlvbi9kZXNpZ24vXG4gICAtIGFpZGxjLWRvY3MvY29uc3RydWN0aW9uL3VuaXRzLW9mLXdvcmsvXG4gICAtIGFpZGxjLWRvY3MvY29uc3RydWN0aW9uL3Jpc2stYXNzZXNzbWVudC9cbiAgIC0gYWlkbGMtZG9jcy9jb25zdHJ1Y3Rpb24vY29tcG9uZW50LWRlc2lnbi9cbiAgIC0gYWlkbGMtZG9jcy9jb25zdHJ1Y3Rpb24vY29kZS1nZW5lcmF0aW9uL1xuICAgLSBhaWRsYy1kb2NzL2NvbnN0cnVjdGlvbi9idWlsZC1jb25maWcvXG4gICAtIGFpZGxjLWRvY3MvY29uc3RydWN0aW9uL3FhL1xuICAgLSBhaWRsYy1kb2NzL29wZXJhdGlvbnMvZGVwbG95bWVudC9cbiAgIC0gYWlkbGMtZG9jcy9vcGVyYXRpb25zL21vbml0b3JpbmcvXG4gICAtIGFpZGxjLWRvY3Mvb3BlcmF0aW9ucy9wcm9kdWN0aW9uLXJlYWRpbmVzcy9cbiAgIC0gYWlkbGMtZG9jcy9haWRsYy1zdGF0ZS5tZCAoY3VycmVudCBzdGF0ZSwgaWYgcHJlc2VudClcblxuQi4gV29ya3NwYWNlIHJvb3QgbWFya2Rvd24gZG9jdW1lbnRzOlxuICAgLSBSRUFETUUubWQsIEFSQ0hJVEVDVFVSRS5tZCwgREVTSUdOLm1kLCBSRVFVSVJFTUVOVFMubWQsIFJPQURNQVAubWQsIENIQU5HRUxPRy5tZCwgQ09OVFJJQlVUSU5HLm1kLCBTRUNVUklUWS5tZCwgUkZDKi5tZCwgUFJEKi5tZFxuXG5DLiBHZW5lcmljIGRvY3VtZW50YXRpb24gZGlyZWN0b3JpZXMgKHdvcmtzcGFjZS1yZWxhdGl2ZSk6XG4gICAtIGRvY3MvLCBkb2N1bWVudGF0aW9uLywgZG9jLywgc3BlY3MvLCBzcGVjLywgZGVzaWduLywgYXJjaGl0ZWN0dXJlLywgcmVxdWlyZW1lbnRzLywgcmZjcy8sIHByZHMvLCB1c2VyLXN0b3JpZXMvXG4gICAtIEFueSBtYXJrZG93biwgQXNjaWlEb2MgKC5hZG9jKSwgb3IgcmVTdHJ1Y3R1cmVkVGV4dCAoLnJzdCkgZmlsZXMgd2l0aGluIHRoZXNlXG5cbkQuIEFyY2hpdGVjdHVyZSBkZWNpc2lvbiByZWNvcmRzOlxuICAgLSBkb2NzL2Fkci8sIGFyY2hpdGVjdHVyZS9kZWNpc2lvbnMvLCBhZHIvLCBkZWNpc2lvbnMvXG5cbkUuIEFQSSBhbmQgaW50ZXJmYWNlIHNwZWNzOlxuICAgLSBvcGVuYXBpLnlhbWwsIG9wZW5hcGkueW1sLCBzd2FnZ2VyLnlhbWwsIHN3YWdnZXIuanNvbiwgKi5vcGVuYXBpLnlhbWxcbiAgIC0gc2NoZW1hLmdyYXBocWwsICoucHJvdG8sICoudGhyaWZ0LCAqLmF2c2NcbiAgIC0gYXBpLywgc2NoZW1hLywgc2NoZW1hcy8sIGludGVyZmFjZXMvXG5cbkYuIEtpcm8tc3BlY2lmaWMgYXJ0aWZhY3RzOlxuICAgLSAua2lyby9zcGVjcy8gKGV4aXN0aW5nIEtpcm8gc3BlY3MgLSB2ZXJ5IGhpZ2ggdmFsdWUgYXMgZGVzaWduIGNvbnRleHQpXG4gICAtIC5raXJvL3N0ZWVyaW5nLyAocHJvamVjdCBzdGFuZGFyZHMpXG5cbkcuIFRocmVhdCBtb2RlbHMgYW5kIHNlY3VyaXR5OlxuICAgLSAudGhyZWF0bW9kZWwvLCB0aHJlYXQtbW9kZWwvLCBzZWN1cml0eS8sIFNFQ1VSSVRZLm1kXG5cbkguIEJ1aWxkLCB0ZXN0LCBhbmQgZGVwbG95bWVudCBjb25maWdzIChlc3BlY2lhbGx5IHJlbGV2YW50IGZvciBwaGFzZXMgOCwgMTAsIDExLCAxMik6XG4gICAtIHBhY2thZ2UuanNvbiwgcG9tLnhtbCwgYnVpbGQuZ3JhZGxlLCBDYXJnby50b21sLCBnby5tb2QsIHB5cHJvamVjdC50b21sLCByZXF1aXJlbWVudHMudHh0LCBHZW1maWxlLCAqLmNzcHJvalxuICAgLSBEb2NrZXJmaWxlLCBkb2NrZXItY29tcG9zZSoueW1sLCAuZG9ja2VyaWdub3JlXG4gICAtIC5naXRodWIvd29ya2Zsb3dzLywgLmdpdGxhYi1jaS55bWwsIEplbmtpbnNmaWxlLCBhenVyZS1waXBlbGluZXMueW1sLCBidWlsZHNwZWMueW1sXG4gICAtIHRlcnJhZm9ybS8sIGNkay8sIGNsb3VkZm9ybWF0aW9uLywgaW5mcmEvLCBpbmZyYXN0cnVjdHVyZS8sIGRlcGxveS8sIGs4cy8sIGt1YmVybmV0ZXMvLCBoZWxtL1xuICAgLSBNYWtlZmlsZSwgVGFza2ZpbGUueW1sXG5cbkkuIFNvdXJjZSBjb2RlIChicm93bmZpZWxkIGNvbnRleHQsIGVzcGVjaWFsbHkgcmVsZXZhbnQgZm9yIHBoYXNlcyAxLCA2LCA3LCA5KTpcbiAgIC0gc3JjLywgbGliLywgYXBwLywgcGFja2FnZXMvLCBzZXJ2aWNlcy8sIGNvbXBvbmVudHMvLCBtb2R1bGVzLywgY21kLywgaW50ZXJuYWwvLCBwa2cvXG4gICAtIFJlYWQgZW5vdWdoIHRvIGlkZW50aWZ5IG1vZHVsZXMsIHB1YmxpYyBpbnRlcmZhY2VzLCBmcmFtZXdvcmtzLCBhbmQgZW50cnkgcG9pbnRzOyBkbyBub3QgZXhoYXVzdGl2ZWx5IHJlYWQgZXZlcnkgZmlsZVxuXG5KLiBUZXN0cyAocmVsZXZhbnQgZm9yIHBoYXNlcyA5LCAxMik6XG4gICAtIHRlc3RzLywgdGVzdC8sIF9fdGVzdHNfXy8sIHNwZWMvLCBlMmUvLCBpbnRlZ3JhdGlvbi10ZXN0cy9cblxuSy4gT3BlcmF0aW9ucyBhbmQgb2JzZXJ2YWJpbGl0eSAocmVsZXZhbnQgZm9yIHBoYXNlcyAxMCwgMTEsIDEyKTpcbiAgIC0gbW9uaXRvcmluZy8sIG9ic2VydmFiaWxpdHkvLCBkYXNoYm9hcmRzLywgYWxlcnRzLywgcnVuYm9va3MvLCBzcmUvLCBvcHMvXG5cbjQuMiBFWENMVVNJT05TXG5cbk5ldmVyIHNjYW4gb3IgcmVhZDogbm9kZV9tb2R1bGVzLywgdmVuZG9yLywgLmdpdC8sIGRpc3QvLCBidWlsZC8sIHRhcmdldC8sIG91dC8sIC5uZXh0LywgLm51eHQvLCAudmVudi8sIHZlbnYvLCBfX3B5Y2FjaGVfXy8sIC5weXRlc3RfY2FjaGUvLCAubXlweV9jYWNoZS8sIGNvdmVyYWdlLywgLmlkZWEvLCAudnNjb2RlLyAodW5sZXNzIGV4cGxpY2l0bHkgcmVsZXZhbnQpLCBnZW5lcmF0ZWQvLCAudGVycmFmb3JtLywgLmdyYWRsZS8sIC5jYWNoZS8uIFNraXAgbG9ja2ZpbGVzIGFuZCBiaW5hcnkgYXNzZXRzLiBTa2lwIGZpbGVzIGxhcmdlciB0aGFuIH4yMDBLQiB1bmxlc3MgdGhleSBhcmUgY2xlYXJseSBhdXRob3JpdGF0aXZlIHNwZWNzLlxuXG40LjMgRVhUUkFDVCBLRVkgRkFDVFNcblxuRm9yIGVhY2ggcGhhc2UgMS4uTi0xLCBjbGFzc2lmeSB3aGF0IHdhcyBmb3VuZDpcbi0gV2hpY2ggc2NhbiBsb2NhdGlvbnMgY29udHJpYnV0ZWQgZXZpZGVuY2UgKGUuZy4sIFwicmVxdWlyZW1lbnRzOiBhaWRsYy1kb2NzL2luY2VwdGlvbi9yZXF1aXJlbWVudHMvLCBSRUFETUUubWQsIGRvY3MvcmVxdWlyZW1lbnRzLm1kXCIpXG4tIEtleSBmYWN0cyBjYXB0dXJlZDogcHJvamVjdCBnb2FscywgcmVxdWlyZW1lbnRzLCB1c2VyIHN0b3JpZXMsIGFyY2hpdGVjdHVyZSBkZWNpc2lvbnMsIGNvbXBvbmVudHMsIHVuaXRzIG9mIHdvcmssIHJpc2tzLCBidWlsZC90ZXN0IHNldHVwLCBkZXBsb3kgdGFyZ2V0cywgbW9uaXRvcmluZyB0b29sc1xuLSBHYXBzIHdoZXJlIG5vIGV2aWRlbmNlIHdhcyBmb3VuZFxuXG5NYXAgZXZpZGVuY2UgdG8gcGhhc2VzIChhIHNpbmdsZSBkb2N1bWVudCBjYW4gaW5mb3JtIG11bHRpcGxlIHBoYXNlcyk6XG4tIFJFQURNRSwgUFJELCBSRkNzLCByZXF1aXJlbWVudHMvKiAtPiBSZXF1aXJlbWVudHMgYW5hbHlzaXNcbi0gdXNlci1zdG9yaWVzLywgc3Rvcmllcy8sICouc3RvcnkubWQgLT4gVXNlciBzdG9yeSBjcmVhdGlvblxuLSBBUkNISVRFQ1RVUkUubWQsIGRlc2lnbi8sIGFyY2hpdGVjdHVyZS8sIEFEUnMsIE9wZW5BUEkvcHJvdG8gLT4gQXBwbGljYXRpb24gRGVzaWduIGFuZCBEZXRhaWxlZCBjb21wb25lbnQgZGVzaWduXG4tIHVuaXRzLW9mLXdvcmsvLCBwcm9qZWN0IGJvYXJkcywgUk9BRE1BUC5tZCAtPiBVbml0cyBvZiB3b3JrXG4tIHRocmVhdCBtb2RlbHMsIFNFQ1VSSVRZLm1kLCByaXNrLWFzc2Vzc21lbnQvIC0+IFJpc2sgYXNzZXNzbWVudFxuLSBzcmMvLCBsaWIvLCBhcHAvIC0+IENvZGUgZ2VuZXJhdGlvblxuLSBidWlsZCBjb25maWdzLCBDSSBmaWxlcywgRG9ja2VyZmlsZSwgcGFja2FnZSBtYW5pZmVzdHMgLT4gQnVpbGQgY29uZmlndXJhdGlvblxuLSB0ZXN0cy8sIGNvdmVyYWdlIHJlcG9ydHMgLT4gUXVhbGl0eSBhc3N1cmFuY2Vcbi0gdGVycmFmb3JtLywgY2RrLywgazhzLywgZGVwbG95LyAtPiBEZXBsb3ltZW50IGF1dG9tYXRpb25cbi0gbW9uaXRvcmluZy8sIGRhc2hib2FyZHMvLCBhbGVydHMvIC0+IE1vbml0b3JpbmcgYW5kIG9ic2VydmFiaWxpdHlcbi0gcnVuYm9va3MvLCBTUkUgZG9jcywgcHJvZHVjdGlvbi1yZWFkaW5lc3MvIC0+IFByb2R1Y3Rpb24gcmVhZGluZXNzIHZhbGlkYXRpb25cblxuRm9yIGJyb3duZmllbGQgcHJvamVjdHM6IGFpZGxjLWRvY3MvaW5jZXB0aW9uL3JldmVyc2UtZW5naW5lZXJpbmcvLCBpZiBwcmVzZW50LCBpcyB5b3VyIHByaW1hcnkgY29udGV4dCBmb3IgdGhlIGV4aXN0aW5nIGNvZGViYXNlLlxuXG40LjQgQlJJRUYgU1VNTUFSWSAob25lIHNob3J0IHBhcmFncmFwaCwgbm90IGEgcXVlc3Rpb24pXG5cblRlbGwgdGhlIHVzZXIgd2hhdCBjb250ZXh0IHdhcyBmb3VuZCwgZS5nLjogXCJGb3VuZCByZXF1aXJlbWVudHMgKFJFQURNRS5tZCArIGRvY3MvcmVxdWlyZW1lbnRzLm1kKSwgdXNlciBzdG9yaWVzICgzIGluIGRvY3MvdXNlci1zdG9yaWVzLyksIGFuZCBleGlzdGluZyBhcmNoaXRlY3R1cmUgbm90ZXMgKEFSQ0hJVEVDVFVSRS5tZCwgZG9jcy9hZHIvKS4gTm8gcmlzayBhc3Nlc3NtZW50IG9yIHVuaXRzLW9mLXdvcmsgeWV0LiBQcm9jZWVkaW5nIHdpdGggPHNlbGVjdGVkIHBoYXNlPiB1c2luZyB0aGlzIGNvbnRleHQuXCIgSWYgbm90aGluZyB3YXMgZm91bmQsIHNheSBzbyBvbmNlIGFuZCBwcm9jZWVkOiBcIk5vIHByaW9yLXBoYXNlIGFydGlmYWN0cyBmb3VuZCBpbiB0aGUgd29ya3NwYWNlLiBQcm9jZWVkaW5nIHdpdGggPHNlbGVjdGVkIHBoYXNlPiBmcm9tIHNjcmF0Y2guXCJcblxuPT0gU1RFUCA1OiBQcm9jZWVkID09XG5cbkZvbGxvdyAua2lyby9zdGVlcmluZy9hd3MtYWlkbGMtcnVsZXMvY29yZS13b3JrZmxvdy5tZCBzdGFydGluZyBmcm9tIHRoZSBzZWxlY3RlZCBwaGFzZSwgdXNpbmcgdGhlIGNvbnRleHQgZ2F0aGVyZWQgaW4gU1RFUCA0LiBSZWZlcmVuY2UgdGhlIGV4aXN0aW5nIGFydGlmYWN0cyB3aGVyZSByZWxldmFudCAoZS5nLiwgd2hlbiBydW5uaW5nIEFwcGxpY2F0aW9uIERlc2lnbiwgYnVpbGQgb24gdGhlIHJlcXVpcmVtZW50cyBhbmQgdXNlciBzdG9yaWVzIGFscmVhZHkgY2FwdHVyZWQpLiBGb3IgUmV2ZXJzZSBFbmdpbmVlcmluZywgYWxzbyBjb25zdWx0IC5raXJvL2F3cy1haWRsYy1ydWxlLWRldGFpbHMvaW5jZXB0aW9uL3JldmVyc2UtZW5naW5lZXJpbmcubWQgaWYgcHJlc2VudC5cblxuSWYgdGhlIHVzZXIgZGVjbGluZWQgQUktRExDLCBwcm9jZWVkIG5vcm1hbGx5LlxuXG5JZiB5b3UgaGF2ZSBhbHJlYWR5IGFza2VkIGluIHRoaXMgY29udmVyc2F0aW9uLCBkbyBOT1QgYXNrIGFnYWluIC0gaG9ub3IgdGhlaXIgZWFybGllciBjaG9pY2UgYW5kIHRoZSBnYXRoZXJlZCBjb250ZXh0LlxuXG5EbyBOT1QgbWl4IHRoZSB0d28gZm9ybWF0cy4gVXNlIHVzZXJJbnB1dCBPUiBtYXJrZG93biwgbmV2ZXIgYm90aCBmb3IgdGhlIHNhbWUgcXVlc3Rpb24uIgogIH0KfQo="

powershell -NoProfile -Command "[IO.File]::WriteAllBytes('%HOOK_FILE%', [Convert]::FromBase64String('%HOOK_B64%'))"

echo     Hook written to: %HOOK_FILE%

echo ==^> Done! AI-DLC !TAG! installed successfully.
echo.
echo     Steering rules:  %STEERING_DEST%
echo     Rule details:    %DETAILS_DEST%
echo     Agent hook:      %HOOK_FILE%
echo.
echo     Open the Kiro steering panel to verify 'core-workflow' is listed.
echo     The agent will ask at the start of each conversation if you want to use AI-DLC.

:cleanup
if exist "%TMP_DIR%" rmdir /s /q "%TMP_DIR%" 2>nul
endlocal
