// SPDX-License-Identifier: Apache-2.0
//
// =============================================================================
// UNIT U4 — bms-interface-adapter — SAFETY-RELEVANT, HUMAN-ENGINEERED
// =============================================================================
// This entire unit is the safety boundary of Chapters 7 and 8. It is the ONLY
// component that talks to the safety-relevant BMS. None of this code is
// generated by AI: it is human-engineered, reviewed, and HIL-verified.
// It satisfies CS-SR-002 (BMS limits authoritative; inhibit honored) and
// CS-SR-003 (loss of interface -> safe idle), with a HARD real-time response.
// =============================================================================

#ifndef BMS_ADAPTER_BMS_TYPES_H
#define BMS_ADAPTER_BMS_TYPES_H

#include <cstdint>

namespace bms_adapter {

// The envelope surfaced to the charge-management service (U3). Mirrors the
// agreed interface contract (charge_management::BmsEnvelope). Fail-safe
// defaults: assume inhibited and invalid until proven otherwise.
struct BmsEnvelope {
  double max_charge_current_a = 0.0;
  bool inhibit = true;
  bool valid = false;
};

// One raw sample read from the BMS over the in-vehicle network/link.
struct BmsSample {
  bool read_ok = false;             // false if the link read failed
  double permitted_current_a = 0.0; // BMS-permitted charge current
  bool inhibit_asserted = true;     // BMS authoritative inhibit (fail-safe: true)
  std::int64_t timestamp_ms = 0;    // monotonic time the sample was taken
};

}  // namespace bms_adapter

#endif  // BMS_ADAPTER_BMS_TYPES_H
